//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HfAnalysisDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HfAnalysisDetail()
        {
            this.HfAnalysisDetail1 = new HashSet<HfAnalysisDetail>();
            this.HfAnalysisRelation = new HashSet<HfAnalysisRelation>();
            this.HfAnalysisRelation1 = new HashSet<HfAnalysisRelation>();
        }
    
        public int HfAnalysisDetailId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastManipulationTime { get; set; }
        public int HedgeFuturesFlowType { get; set; }
        public Nullable<int> BuySpotRequestId { get; set; }
        public Nullable<int> SellSpotRequestId { get; set; }
        public Nullable<int> BuyFuturesRecordId { get; set; }
        public Nullable<int> SellFuturesRecordId { get; set; }
        public Nullable<int> DefaultCargoUnitId { get; set; }
        public Nullable<int> HfFlowId { get; set; }
        public Nullable<decimal> DefaultCargoUnitQuantity { get; set; }
        public Nullable<int> PrecursorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HfAnalysisDetail> HfAnalysisDetail1 { get; set; }
        public virtual HfAnalysisDetail HfAnalysisDetail2 { get; set; }
        public virtual HfFlow HfFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HfAnalysisRelation> HfAnalysisRelation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HfAnalysisRelation> HfAnalysisRelation1 { get; set; }
    }
}
