//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HfFlowGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HfFlowGroup()
        {
            this.HfFlow = new HashSet<HfFlow>();
        }
    
        public int HfFlowGroupId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastManipulationTime { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public string Note { get; set; }
        public int HfFlowCategory { get; set; }
        public int HedgeFuturesFlowType { get; set; }
        public bool Hedge_SpotIsBuy { get; set; }
        public bool Carry_Futures1IsBuy { get; set; }
        public Nullable<int> PricingVarietyId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public Nullable<bool> IsOneOne { get; set; }
        public Nullable<bool> IsMatchReferenceCode { get; set; }
        public Nullable<int> MatchPriority { get; set; }
        public Nullable<decimal> PriceLbmtr { get; set; }
        public Nullable<decimal> PriceUbmtr { get; set; }
        public Nullable<decimal> CargoLbmtr { get; set; }
        public Nullable<decimal> CargoUbmtr { get; set; }
        public Nullable<int> BuyMarketId { get; set; }
        public Nullable<int> BuyInstrumentCategoryId { get; set; }
        public string BuyInstrumentContractCode { get; set; }
        public Nullable<int> BuyInstrumentId { get; set; }
        public Nullable<int> SellMarketId { get; set; }
        public Nullable<int> SellInstrumentCategoryId { get; set; }
        public string SellInstrumentContractCode { get; set; }
        public Nullable<int> SellInstrumentId { get; set; }
        public string CarryStrategyInstance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HfFlow> HfFlow { get; set; }
    }
}
