//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HfFlow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HfFlow()
        {
            this.HfAnalysisDetail = new HashSet<HfAnalysisDetail>();
        }
    
        public int HfFlowId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastManipulationTime { get; set; }
        public int HfFlowCategory { get; set; }
        public int HedgeFuturesFlowType { get; set; }
        public int HfFlowSourceType { get; set; }
        public Nullable<int> Balance_BuySpotId { get; set; }
        public Nullable<int> Balance_SellSpotId { get; set; }
        public Nullable<int> Hedge_SpotId { get; set; }
        public Nullable<int> Hedge_FuturesId { get; set; }
        public bool Hedge_SpotIsBuy { get; set; }
        public Nullable<bool> Hedge_FuturesIsWind { get; set; }
        public Nullable<int> Unwind_Futures1Id { get; set; }
        public Nullable<int> Unwind_Futures2Id { get; set; }
        public bool Unwind_Futures1IsBuy { get; set; }
        public Nullable<int> Carry_Futures1Id { get; set; }
        public Nullable<int> Carry_Futures2Id { get; set; }
        public bool Carry_Futures1IsBuy { get; set; }
        public Nullable<int> BuySpotRequestId { get; set; }
        public Nullable<int> SellSpotRequestId { get; set; }
        public Nullable<int> BuyFuturesRecordId { get; set; }
        public Nullable<int> SellFuturesRecordId { get; set; }
        public Nullable<int> DefaultCargoUnitId { get; set; }
        public Nullable<decimal> DefaultCargoUnitQuantity { get; set; }
        public Nullable<int> BuyCargoUnitId { get; set; }
        public Nullable<decimal> BuyCargoQuantity { get; set; }
        public Nullable<int> SellCargoUnitId { get; set; }
        public Nullable<decimal> SellCargoQuantity { get; set; }
        public Nullable<int> HfFlowGroupId { get; set; }
        public bool AnalysisIsSrcBuy { get; set; }
        public Nullable<bool> AssignedIsSrcBuy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HfAnalysisDetail> HfAnalysisDetail { get; set; }
        public virtual HfFuturesOrder HfFuturesOrder { get; set; }
        public virtual HfSpotRequest HfSpotRequest { get; set; }
        public virtual HfFuturesOrder HfFuturesOrder1 { get; set; }
        public virtual HfSpotRequest HfSpotRequest1 { get; set; }
        public virtual HfFlowGroup HfFlowGroup { get; set; }
        public virtual HfFuturesOrder HfFuturesOrder2 { get; set; }
        public virtual HfSpotRequest HfSpotRequest2 { get; set; }
    }
}
