//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HfFuturesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HfFuturesOrder()
        {
            this.HfFlow = new HashSet<HfFlow>();
            this.HfFlow1 = new HashSet<HfFlow>();
            this.HfFlow2 = new HashSet<HfFlow>();
        }
    
        public int WFFutureTradeRecordId { get; set; }
        public string AccountOrder { get; set; }
        public Nullable<int> TraderId { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public Nullable<int> TradeAccountId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public string InstrumentContractCode { get; set; }
        public Nullable<int> MarketId { get; set; }
        public Nullable<int> InstrumentCategoryId { get; set; }
        public Nullable<decimal> AverageFilledPrice { get; set; }
        public Nullable<decimal> FilledLotsCount { get; set; }
        public Nullable<System.DateTime> LastFilledTime { get; set; }
        public bool IsBuy { get; set; }
        public Nullable<bool> IsHistory { get; set; }
        public Nullable<bool> IsClose { get; set; }
        public Nullable<int> FutureTradePurpose { get; set; }
        public Nullable<System.DateTime> TradingDay { get; set; }
        public Nullable<System.DateTime> LastManipulationTime { get; set; }
        public bool IsDeleted { get; set; }
        public int SourceType { get; set; }
        public Nullable<decimal> FilledQuantity { get; set; }
        public Nullable<decimal> HedgingCoefficient { get; set; }
        public Nullable<decimal> PricingCargoQuantity { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string AgentOrder { get; set; }
        public Nullable<long> OrderAccountingId { get; set; }
        public string CarryStrategyInstance { get; set; }
        public Nullable<decimal> WindedFilledLotsCount { get; set; }
        public Nullable<decimal> UnwoundFilledLotsCount { get; set; }
        public Nullable<int> CargoUnitId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> LotSize { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> CommentCarryFlag { get; set; }
        public string ReferenceCode { get; set; }
        public string OrderRequestCustomerName { get; set; }
        public Nullable<decimal> OrderRequestCargoQuantity { get; set; }
        public Nullable<decimal> OrderRequestBasePrice { get; set; }
        public Nullable<decimal> FormerShortPosition { get; set; }
        public Nullable<decimal> WindedPricingCargoQuantity { get; set; }
        public Nullable<decimal> UnwoundPricingCargoQuantity { get; set; }
        public Nullable<decimal> DefaultCargoUnitQuantity { get; set; }
        public Nullable<decimal> AnalysisFlowInQuantity { get; set; }
        public Nullable<decimal> AnalysisFlowOutQuantity { get; set; }
        public Nullable<decimal> DefaultUnitHedgeFlowQuantity { get; set; }
        public Nullable<decimal> DefaultUnitCarryFlowQuantity { get; set; }
        public Nullable<decimal> HedgeFlowQuantity { get; set; }
        public Nullable<decimal> CarryFlowQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HfFlow> HfFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HfFlow> HfFlow1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HfFlow> HfFlow2 { get; set; }
        public virtual WFInstrumentCategory WFInstrumentCategory { get; set; }
    }
}
