//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class HfSpotRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HfSpotRequest()
        {
            this.HfFlow = new HashSet<HfFlow>();
            this.HfFlow1 = new HashSet<HfFlow>();
            this.HfFlow2 = new HashSet<HfFlow>();
        }
    
        public int HfSpotRequestId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastManipulationTime { get; set; }
        public Nullable<long> SpotPricingId { get; set; }
        public bool IsBuySpot { get; set; }
        public bool IsUnpriced { get; set; }
        public Nullable<int> PricingVarietyId { get; set; }
        public Nullable<int> CargoQuantityTypeId { get; set; }
        public Nullable<int> CargoUnitId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> CargoQuantity { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<System.DateTime> PricingDate { get; set; }
        public Nullable<int> InstrumentId { get; set; }
        public Nullable<int> InstrumentCategoryId { get; set; }
        public Nullable<int> MarketId { get; set; }
        public string SalesName { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> DefaultCargoUnitQuantity { get; set; }
        public Nullable<decimal> DefaultUnitSpotBalancedQuantity { get; set; }
        public Nullable<decimal> DefaultUnitHedgedQuantity { get; set; }
        public Nullable<decimal> SpotBalancedQuantity { get; set; }
        public Nullable<decimal> HedgedQuantity { get; set; }
        public string ReferenceCode { get; set; }
        public Nullable<int> IntegrationPricedType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HfFlow> HfFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HfFlow> HfFlow1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HfFlow> HfFlow2 { get; set; }
    }
}
