//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Data;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class OperationSystem_HBMSEntities : DbContext
    {
        public OperationSystem_HBMSEntities()
            : base("name=OperationSystem_HBMSEntities")
        {
            Configuration.LazyLoadingEnabled = false;
            Configuration.ProxyCreationEnabled = false;
            Configuration.UseDatabaseNullSemantics = true;
        }
        public string NameOrConnectionString { get; }

        public OperationSystem_HBMSEntities(string nameOrConnectionString)
            : base(nameOrConnectionString)
        {
            this.NameOrConnectionString = nameOrConnectionString;

            this.Configuration.LazyLoadingEnabled = false;

            this.Configuration.ProxyCreationEnabled = false;

            this.Database.Connection.StateChange += this.OnStateChange;

        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HfAnalysisDetail> HfAnalysisDetail { get; set; }
        public virtual DbSet<HfAnalysisRelation> HfAnalysisRelation { get; set; }
        public virtual DbSet<HfFlow> HfFlow { get; set; }
        public virtual DbSet<HfFlowGroup> HfFlowGroup { get; set; }
        public virtual DbSet<HfFuturesOrder> HfFuturesOrder { get; set; }
        public virtual DbSet<HfSpotRequest> HfSpotRequest { get; set; }
        public virtual DbSet<HfTask> HfTask { get; set; }
        public virtual DbSet<OnlineTime> OnlineTime { get; set; }
        public virtual DbSet<OnlineTimeFlag> OnlineTimeFlag { get; set; }
        public virtual DbSet<SpotTradeProcessingFlag> SpotTradeProcessingFlag { get; set; }
        public virtual DbSet<SyncContractDetail> SyncContractDetail { get; set; }
        public virtual DbSet<SyncFreightCharge> SyncFreightCharge { get; set; }
        public virtual DbSet<SynchronizationErrorLog> SynchronizationErrorLog { get; set; }
        public virtual DbSet<SyncOutRecordSameTransport> SyncOutRecordSameTransport { get; set; }
        public virtual DbSet<SyncSpotInventory> SyncSpotInventory { get; set; }
        public virtual DbSet<SyncSpotMortgage> SyncSpotMortgage { get; set; }
        public virtual DbSet<SyncSpotTrade> SyncSpotTrade { get; set; }
        public virtual DbSet<SyncTradeContractInfo> SyncTradeContractInfo { get; set; }
        public virtual DbSet<SyncTradeDeliveryBatch> SyncTradeDeliveryBatch { get; set; }
        public virtual DbSet<SyncTradePayment> SyncTradePayment { get; set; }
        public virtual DbSet<SyncTradePriced> SyncTradePriced { get; set; }
        public virtual DbSet<TpProject> TpProject { get; set; }
        public virtual DbSet<TpProjectImplementation> TpProjectImplementation { get; set; }
        public virtual DbSet<WFAccountEntity> WFAccountEntity { get; set; }
        public virtual DbSet<WFAccountingDataLog> WFAccountingDataLog { get; set; }
        public virtual DbSet<WFAccountingDataLogDetail> WFAccountingDataLogDetail { get; set; }
        public virtual DbSet<WFAccountingFee> WFAccountingFee { get; set; }
        public virtual DbSet<WFAccountingTask> WFAccountingTask { get; set; }
        public virtual DbSet<WFActualApprovalStep> WFActualApprovalStep { get; set; }
        public virtual DbSet<WFActualApprovalStepUser> WFActualApprovalStepUser { get; set; }
        public virtual DbSet<WFActualApprovalWF> WFActualApprovalWF { get; set; }
        public virtual DbSet<WFActualApprover> WFActualApprover { get; set; }
        public virtual DbSet<WFActualStepCondition> WFActualStepCondition { get; set; }
        public virtual DbSet<WFActuaStepAction> WFActuaStepAction { get; set; }
        public virtual DbSet<WFAdditionalConfiguration> WFAdditionalConfiguration { get; set; }
        public virtual DbSet<WFAggregateBill> WFAggregateBill { get; set; }
        public virtual DbSet<WFAggregateBillDetail> WFAggregateBillDetail { get; set; }
        public virtual DbSet<WFAmountRecord> WFAmountRecord { get; set; }
        public virtual DbSet<WFAmountRecordDetail> WFAmountRecordDetail { get; set; }
        public virtual DbSet<WFAmountRecordSubDetail> WFAmountRecordSubDetail { get; set; }
        public virtual DbSet<WFApprovalAttachment> WFApprovalAttachment { get; set; }
        public virtual DbSet<WFApprovalCancellationForm> WFApprovalCancellationForm { get; set; }
        public virtual DbSet<WFApprovalConfiguration> WFApprovalConfiguration { get; set; }
        public virtual DbSet<WFApprovalWorkflowLog> WFApprovalWorkflowLog { get; set; }
        public virtual DbSet<WFApprovalWorkflowStepTemplate> WFApprovalWorkflowStepTemplate { get; set; }
        public virtual DbSet<WFApprovalWorkflowTemplate> WFApprovalWorkflowTemplate { get; set; }
        public virtual DbSet<WFApprovalWorkflowTemplateRole> WFApprovalWorkflowTemplateRole { get; set; }
        public virtual DbSet<WFApproverTemplate> WFApproverTemplate { get; set; }
        public virtual DbSet<WFAuthorization> WFAuthorization { get; set; }
        public virtual DbSet<WFAuthorizationContent> WFAuthorizationContent { get; set; }
        public virtual DbSet<WFAvgPriceDetail> WFAvgPriceDetail { get; set; }
        public virtual DbSet<WFBillContentArchive> WFBillContentArchive { get; set; }
        public virtual DbSet<WFBillContentPrint> WFBillContentPrint { get; set; }
        public virtual DbSet<WFBillTemplate> WFBillTemplate { get; set; }
        public virtual DbSet<WFBrand> WFBrand { get; set; }
        public virtual DbSet<WFBusiness> WFBusiness { get; set; }
        public virtual DbSet<WFBusinessBillTemplate> WFBusinessBillTemplate { get; set; }
        public virtual DbSet<WFBuyContractTradeRecord> WFBuyContractTradeRecord { get; set; }
        public virtual DbSet<WFCardCodeInfo> WFCardCodeInfo { get; set; }
        public virtual DbSet<WFCargoInseparabilityConfiguration> WFCargoInseparabilityConfiguration { get; set; }
        public virtual DbSet<WFCargoValueCalcConf> WFCargoValueCalcConf { get; set; }
        public virtual DbSet<WFCarry> WFCarry { get; set; }
        public virtual DbSet<WFCodeCustomization> WFCodeCustomization { get; set; }
        public virtual DbSet<WFCodeTemplate> WFCodeTemplate { get; set; }
        public virtual DbSet<WFCodeTemplateDetail> WFCodeTemplateDetail { get; set; }
        public virtual DbSet<WFCommercialInvoice> WFCommercialInvoice { get; set; }
        public virtual DbSet<WFCommodity> WFCommodity { get; set; }
        public virtual DbSet<WFCommodityCategory> WFCommodityCategory { get; set; }
        public virtual DbSet<WFCommodityQuantityUnit> WFCommodityQuantityUnit { get; set; }
        public virtual DbSet<WFCommodityType> WFCommodityType { get; set; }
        public virtual DbSet<WFCommodityTypeQuantityUnit> WFCommodityTypeQuantityUnit { get; set; }
        public virtual DbSet<WFCompany> WFCompany { get; set; }
        public virtual DbSet<WFCompanyBankInfo> WFCompanyBankInfo { get; set; }
        public virtual DbSet<WFCompanyBankInfoCommodityAccountEntity> WFCompanyBankInfoCommodityAccountEntity { get; set; }
        public virtual DbSet<WFCompanyBusiness> WFCompanyBusiness { get; set; }
        public virtual DbSet<WFCompanySAPCode> WFCompanySAPCode { get; set; }
        public virtual DbSet<WFComponentVariety> WFComponentVariety { get; set; }
        public virtual DbSet<WFCondition> WFCondition { get; set; }
        public virtual DbSet<WFConditionProperty> WFConditionProperty { get; set; }
        public virtual DbSet<WFContact> WFContact { get; set; }
        public virtual DbSet<WFContactCommodityAccountEntity> WFContactCommodityAccountEntity { get; set; }
        public virtual DbSet<WFContractBillArchive> WFContractBillArchive { get; set; }
        public virtual DbSet<WFContractBillArchiveDetail> WFContractBillArchiveDetail { get; set; }
        public virtual DbSet<WFContractBillArchiveLinker> WFContractBillArchiveLinker { get; set; }
        public virtual DbSet<WFContractComment> WFContractComment { get; set; }
        public virtual DbSet<WFContractComponent> WFContractComponent { get; set; }
        public virtual DbSet<WFContractCustomer> WFContractCustomer { get; set; }
        public virtual DbSet<WFContractDetailInfo> WFContractDetailInfo { get; set; }
        public virtual DbSet<WFContractDetailQuantity> WFContractDetailQuantity { get; set; }
        public virtual DbSet<WFContractEntryRecordDetail> WFContractEntryRecordDetail { get; set; }
        public virtual DbSet<WFContractFee> WFContractFee { get; set; }
        public virtual DbSet<WFContractFeeType> WFContractFeeType { get; set; }
        public virtual DbSet<WFContractInfo> WFContractInfo { get; set; }
        public virtual DbSet<WFContractInvoice> WFContractInvoice { get; set; }
        public virtual DbSet<WFContractLog> WFContractLog { get; set; }
        public virtual DbSet<WFContractOutRecordDetail> WFContractOutRecordDetail { get; set; }
        public virtual DbSet<WFContractPricingTerm> WFContractPricingTerm { get; set; }
        public virtual DbSet<WFContractSecondPart> WFContractSecondPart { get; set; }
        public virtual DbSet<WFContractWhole> WFContractWhole { get; set; }
        public virtual DbSet<WFCorporationApprovalWFTemplate> WFCorporationApprovalWFTemplate { get; set; }
        public virtual DbSet<WFCorporationDepartment> WFCorporationDepartment { get; set; }
        public virtual DbSet<WFCorporationTypeConfiguration> WFCorporationTypeConfiguration { get; set; }
        public virtual DbSet<WFCostPayRecord> WFCostPayRecord { get; set; }
        public virtual DbSet<WFCostPayRequest> WFCostPayRequest { get; set; }
        public virtual DbSet<WFCostPrice> WFCostPrice { get; set; }
        public virtual DbSet<WFCreditRating> WFCreditRating { get; set; }
        public virtual DbSet<WFCreditRatingDetail> WFCreditRatingDetail { get; set; }
        public virtual DbSet<WFCurrency> WFCurrency { get; set; }
        public virtual DbSet<WFCurrencyPair> WFCurrencyPair { get; set; }
        public virtual DbSet<WFCustomerCommodity> WFCustomerCommodity { get; set; }
        public virtual DbSet<WFDateVaryingPropertyConf> WFDateVaryingPropertyConf { get; set; }
        public virtual DbSet<WFDefaultExchangeSetting> WFDefaultExchangeSetting { get; set; }
        public virtual DbSet<WFDeliveryContract> WFDeliveryContract { get; set; }
        public virtual DbSet<WFDeliveryInDetailQuantity> WFDeliveryInDetailQuantity { get; set; }
        public virtual DbSet<WFDeliveryNotification> WFDeliveryNotification { get; set; }
        public virtual DbSet<WFDeliveryNotificationDetail> WFDeliveryNotificationDetail { get; set; }
        public virtual DbSet<WFDeliveryNotificationObject> WFDeliveryNotificationObject { get; set; }
        public virtual DbSet<WFDepartmentAccountEntity> WFDepartmentAccountEntity { get; set; }
        public virtual DbSet<WFDeposit> WFDeposit { get; set; }
        public virtual DbSet<WFDepositContract> WFDepositContract { get; set; }
        public virtual DbSet<WFEntityProperty> WFEntityProperty { get; set; }
        public virtual DbSet<WFEntityPropertyType> WFEntityPropertyType { get; set; }
        public virtual DbSet<WFEntitySapPart> WFEntitySapPart { get; set; }
        public virtual DbSet<WFExchangeBill> WFExchangeBill { get; set; }
        public virtual DbSet<WFExchangeRate> WFExchangeRate { get; set; }
        public virtual DbSet<WFExportTradeRecord> WFExportTradeRecord { get; set; }
        public virtual DbSet<WFExportWarehouseStorage> WFExportWarehouseStorage { get; set; }
        public virtual DbSet<WFFeeEstimate> WFFeeEstimate { get; set; }
        public virtual DbSet<WFFeeRecord> WFFeeRecord { get; set; }
        public virtual DbSet<WFFinalPrice> WFFinalPrice { get; set; }
        public virtual DbSet<WFFinancialBatch> WFFinancialBatch { get; set; }
        public virtual DbSet<WFFinancialBatchInventory> WFFinancialBatchInventory { get; set; }
        public virtual DbSet<WFFinancialBatchOutDetail> WFFinancialBatchOutDetail { get; set; }
        public virtual DbSet<WFFirePriceConfirm> WFFirePriceConfirm { get; set; }
        public virtual DbSet<WFFirePriceDetail> WFFirePriceDetail { get; set; }
        public virtual DbSet<WFFirePricePostponeConfirm> WFFirePricePostponeConfirm { get; set; }
        public virtual DbSet<WFFirePriceRecord> WFFirePriceRecord { get; set; }
        public virtual DbSet<WFFreightPrice> WFFreightPrice { get; set; }
        public virtual DbSet<WFFutureTradeRecord> WFFutureTradeRecord { get; set; }
        public virtual DbSet<WFGeneralModification> WFGeneralModification { get; set; }
        public virtual DbSet<WFGeneralModificationDetail> WFGeneralModificationDetail { get; set; }
        public virtual DbSet<WFHedgeMatch> WFHedgeMatch { get; set; }
        public virtual DbSet<WFInstrument> WFInstrument { get; set; }
        public virtual DbSet<WFInstrumentCategory> WFInstrumentCategory { get; set; }
        public virtual DbSet<WFInstrumentSettlementPrice> WFInstrumentSettlementPrice { get; set; }
        public virtual DbSet<WFInventoryAdjustmentRequest> WFInventoryAdjustmentRequest { get; set; }
        public virtual DbSet<WFInvoiceDetailQuantity> WFInvoiceDetailQuantity { get; set; }
        public virtual DbSet<WFInvoiceObject> WFInvoiceObject { get; set; }
        public virtual DbSet<WFInvoiceRecord> WFInvoiceRecord { get; set; }
        public virtual DbSet<WFInvoiceRequest> WFInvoiceRequest { get; set; }
        public virtual DbSet<WFInvoiceRequestDetail> WFInvoiceRequestDetail { get; set; }
        public virtual DbSet<WFLcContract> WFLcContract { get; set; }
        public virtual DbSet<WFLetterOfCredit> WFLetterOfCredit { get; set; }
        public virtual DbSet<WFLoginHistory> WFLoginHistory { get; set; }
        public virtual DbSet<WFLogisticsPlace> WFLogisticsPlace { get; set; }
        public virtual DbSet<WFLongContract> WFLongContract { get; set; }
        public virtual DbSet<WFLongContractDetail> WFLongContractDetail { get; set; }
        public virtual DbSet<WFMarketCalendar> WFMarketCalendar { get; set; }
        public virtual DbSet<WFMarketPriceDiff> WFMarketPriceDiff { get; set; }
        public virtual DbSet<WFMoneyConversion> WFMoneyConversion { get; set; }
        public virtual DbSet<WFMultiPrecursorBatch> WFMultiPrecursorBatch { get; set; }
        public virtual DbSet<WFOfficeAddress> WFOfficeAddress { get; set; }
        public virtual DbSet<WFOrderInfo> WFOrderInfo { get; set; }
        public virtual DbSet<WFOtherBill> WFOtherBill { get; set; }
        public virtual DbSet<WFOurPlantTransferWarehouseNotification> WFOurPlantTransferWarehouseNotification { get; set; }
        public virtual DbSet<WFOurPlantTransferWarehouseNotificationDetail> WFOurPlantTransferWarehouseNotificationDetail { get; set; }
        public virtual DbSet<WFOutRecordAssistantMeasureInfo> WFOutRecordAssistantMeasureInfo { get; set; }
        public virtual DbSet<WFPaymentProposal> WFPaymentProposal { get; set; }
        public virtual DbSet<WFPaymentProposalDetail> WFPaymentProposalDetail { get; set; }
        public virtual DbSet<WFPaymentProposalSubDetail> WFPaymentProposalSubDetail { get; set; }
        public virtual DbSet<WFPayRequest> WFPayRequest { get; set; }
        public virtual DbSet<WFPayRequestDetail> WFPayRequestDetail { get; set; }
        public virtual DbSet<WFPayRequestSubDetail> WFPayRequestSubDetail { get; set; }
        public virtual DbSet<WFPledgeContract> WFPledgeContract { get; set; }
        public virtual DbSet<WFPledgeInfo> WFPledgeInfo { get; set; }
        public virtual DbSet<WFPledgeRenewal> WFPledgeRenewal { get; set; }
        public virtual DbSet<WFPledgeRenewalDetail> WFPledgeRenewalDetail { get; set; }
        public virtual DbSet<WFPost> WFPost { get; set; }
        public virtual DbSet<WFPostingInfo> WFPostingInfo { get; set; }
        public virtual DbSet<WFPostingInfoDetail> WFPostingInfoDetail { get; set; }
        public virtual DbSet<WFPriceConfirmationLetter> WFPriceConfirmationLetter { get; set; }
        public virtual DbSet<WFPriceConfirmationLetterDetails> WFPriceConfirmationLetterDetails { get; set; }
        public virtual DbSet<WFPriceDetail> WFPriceDetail { get; set; }
        public virtual DbSet<WFPriceInfo> WFPriceInfo { get; set; }
        public virtual DbSet<WFPriceInstrument> WFPriceInstrument { get; set; }
        public virtual DbSet<WFPriceQuantityScale> WFPriceQuantityScale { get; set; }
        public virtual DbSet<WFPricingConfirmDetail> WFPricingConfirmDetail { get; set; }
        public virtual DbSet<WFQuantityType> WFQuantityType { get; set; }
        public virtual DbSet<WFReceivingClaim> WFReceivingClaim { get; set; }
        public virtual DbSet<WFRoleBusiness> WFRoleBusiness { get; set; }
        public virtual DbSet<WFRoleConditionConfiguration> WFRoleConditionConfiguration { get; set; }
        public virtual DbSet<WFRoleInfo> WFRoleInfo { get; set; }
        public virtual DbSet<WFRolePrivilege> WFRolePrivilege { get; set; }
        public virtual DbSet<WFSafetyLink> WFSafetyLink { get; set; }
        public virtual DbSet<WFSaleContractTradeRecord> WFSaleContractTradeRecord { get; set; }
        public virtual DbSet<WFSapAmountCategoryCommodity> WFSapAmountCategoryCommodity { get; set; }
        public virtual DbSet<WFSapConfiguration> WFSapConfiguration { get; set; }
        public virtual DbSet<WFSapTransaction> WFSapTransaction { get; set; }
        public virtual DbSet<WFSapTransactionMultiObject> WFSapTransactionMultiObject { get; set; }
        public virtual DbSet<WFSettlementRequest> WFSettlementRequest { get; set; }
        public virtual DbSet<WFSettlementRequestDetail> WFSettlementRequestDetail { get; set; }
        public virtual DbSet<WFSettleOption> WFSettleOption { get; set; }
        public virtual DbSet<WFSettleOptionDetail> WFSettleOptionDetail { get; set; }
        public virtual DbSet<WFSettleOptionDetailExchangeProcess> WFSettleOptionDetailExchangeProcess { get; set; }
        public virtual DbSet<WFSettleOptionDetailPaymentForm> WFSettleOptionDetailPaymentForm { get; set; }
        public virtual DbSet<WFSodEpAmountFirst> WFSodEpAmountFirst { get; set; }
        public virtual DbSet<WFSodEpConditionalRelease> WFSodEpConditionalRelease { get; set; }
        public virtual DbSet<WFSodEpDocumentsAgainstAcceptance> WFSodEpDocumentsAgainstAcceptance { get; set; }
        public virtual DbSet<WFSodEpDocumentsAgainstPayment> WFSodEpDocumentsAgainstPayment { get; set; }
        public virtual DbSet<WFSodEpLetterOfCredit> WFSodEpLetterOfCredit { get; set; }
        public virtual DbSet<WFSodPfExchangeBill> WFSodPfExchangeBill { get; set; }
        public virtual DbSet<WFSpecialFeeConfiguration> WFSpecialFeeConfiguration { get; set; }
        public virtual DbSet<WFSpecification> WFSpecification { get; set; }
        public virtual DbSet<WFSpotReceiptConvertDetailInfo> WFSpotReceiptConvertDetailInfo { get; set; }
        public virtual DbSet<WFSpotReceiptConvertInfo> WFSpotReceiptConvertInfo { get; set; }
        public virtual DbSet<WFStepActionTemplate> WFStepActionTemplate { get; set; }
        public virtual DbSet<WFStepConditionTemplate> WFStepConditionTemplate { get; set; }
        public virtual DbSet<WFStorageAssistantMeasureInfo> WFStorageAssistantMeasureInfo { get; set; }
        public virtual DbSet<WFStorageConversion> WFStorageConversion { get; set; }
        public virtual DbSet<WFStorageConversionDetail> WFStorageConversionDetail { get; set; }
        public virtual DbSet<WFSubscribeConfig> WFSubscribeConfig { get; set; }
        public virtual DbSet<WFSubscribeConfigDetail> WFSubscribeConfigDetail { get; set; }
        public virtual DbSet<WFSupplementalAgreement> WFSupplementalAgreement { get; set; }
        public virtual DbSet<WFSupplementalAgreementDetail> WFSupplementalAgreementDetail { get; set; }
        public virtual DbSet<WFSystemCodeInfo> WFSystemCodeInfo { get; set; }
        public virtual DbSet<WFSystemCodeInfoConfiguration> WFSystemCodeInfoConfiguration { get; set; }
        public virtual DbSet<WFSystemConfigDetail> WFSystemConfigDetail { get; set; }
        public virtual DbSet<WFSystemConfiguration> WFSystemConfiguration { get; set; }
        public virtual DbSet<WFSystemFee> WFSystemFee { get; set; }
        public virtual DbSet<WFSystemFeeConfiguration> WFSystemFeeConfiguration { get; set; }
        public virtual DbSet<WFSystemFinanceAccount> WFSystemFinanceAccount { get; set; }
        public virtual DbSet<WFSystemLog> WFSystemLog { get; set; }
        public virtual DbSet<WFTempData> WFTempData { get; set; }
        public virtual DbSet<WFTradeAccount> WFTradeAccount { get; set; }
        public virtual DbSet<WFTradeInstruction> WFTradeInstruction { get; set; }
        public virtual DbSet<WFTradeInstructionDetail> WFTradeInstructionDetail { get; set; }
        public virtual DbSet<WFTradeInstructionRelation> WFTradeInstructionRelation { get; set; }
        public virtual DbSet<WFTradePricing> WFTradePricing { get; set; }
        public virtual DbSet<WFTradePricingMatchDetail> WFTradePricingMatchDetail { get; set; }
        public virtual DbSet<WFTradePricingMatchRecord> WFTradePricingMatchRecord { get; set; }
        public virtual DbSet<WFTradingStrategy> WFTradingStrategy { get; set; }
        public virtual DbSet<WFUnit> WFUnit { get; set; }
        public virtual DbSet<WFUnitConversion> WFUnitConversion { get; set; }
        public virtual DbSet<WFUnPledgeInfo> WFUnPledgeInfo { get; set; }
        public virtual DbSet<WFUser> WFUser { get; set; }
        public virtual DbSet<WFUserBusiness> WFUserBusiness { get; set; }
        public virtual DbSet<WFUserCorporation> WFUserCorporation { get; set; }
        public virtual DbSet<WFUserLinker> WFUserLinker { get; set; }
        public virtual DbSet<WFUserMessage> WFUserMessage { get; set; }
        public virtual DbSet<WFUserPublishInformation> WFUserPublishInformation { get; set; }
        public virtual DbSet<WFUserRequest> WFUserRequest { get; set; }
        public virtual DbSet<WFUserRole> WFUserRole { get; set; }
        public virtual DbSet<WFUserTask> WFUserTask { get; set; }
        public virtual DbSet<WFVehicleTransportSpec> WFVehicleTransportSpec { get; set; }
        public virtual DbSet<WFWarehouseCalculateFeeType> WFWarehouseCalculateFeeType { get; set; }
        public virtual DbSet<WFWarehouseCardCodePrefix> WFWarehouseCardCodePrefix { get; set; }
        public virtual DbSet<WFWarehouseCompany> WFWarehouseCompany { get; set; }
        public virtual DbSet<WFWarehouseDetail> WFWarehouseDetail { get; set; }
        public virtual DbSet<WFWarehouseEntryRecord> WFWarehouseEntryRecord { get; set; }
        public virtual DbSet<WFWarehouseEntryRecordDetail> WFWarehouseEntryRecordDetail { get; set; }
        public virtual DbSet<WFWarehouseOutOrder> WFWarehouseOutOrder { get; set; }
        public virtual DbSet<WFWarehouseOutRecord> WFWarehouseOutRecord { get; set; }
        public virtual DbSet<WFWarehouseOutRecordDetail> WFWarehouseOutRecordDetail { get; set; }
        public virtual DbSet<WFWarehouseShiftingRecord> WFWarehouseShiftingRecord { get; set; }
        public virtual DbSet<WFWarehouseStorage> WFWarehouseStorage { get; set; }
        public virtual DbSet<WFWarehouseStorageHistory> WFWarehouseStorageHistory { get; set; }
        public virtual DbSet<WFWarehouseStorageItem> WFWarehouseStorageItem { get; set; }
        public virtual DbSet<WFWarehousing> WFWarehousing { get; set; }
        public virtual DbSet<WFWarehousingDetail> WFWarehousingDetail { get; set; }
        public virtual DbSet<WFWhStorageFlowTrack> WFWhStorageFlowTrack { get; set; }
        public virtual DbSet<SpotMortgageProcessingFlag> SpotMortgageProcessingFlag { get; set; }
        private void OnStateChange(object sender, StateChangeEventArgs args)
        {
            if (args.CurrentState == ConnectionState.Open && args.OriginalState != ConnectionState.Open)
            {
                using (var command = this.Database.Connection.CreateCommand())
                {
                    var isolationLevel = this.GetCurrentTransactionScopeDataIsolationLevel();
                    string commandText = this.CommandTextSetTransactionIsolationLevel(isolationLevel);

                    command.CommandText = commandText;
                    command.ExecuteNonQuery();
                }
            }
        }

        private static bool _ReadCommittedSnapshot { get; } = true;
        private static bool _AllowSnapshotIsolation { get; } = true;

        private static System.Data.IsolationLevel _DefaultIsolationLevel { get; } = _AllowSnapshotIsolation ? IsolationLevel.Snapshot : IsolationLevel.ReadCommitted;

        private const string CommandTextGetTransactionIsolationLevel = @"select transaction_isolation_level from sys.dm_exec_sessions where session_id = @@spid";

        public bool ReadCommittedSnapshotOn
        {
            get
            {
                return _ReadCommittedSnapshot;
            }
        }

        public bool AllowSnapshotIsolation
        {
            get
            {
                return _AllowSnapshotIsolation;
            }
        }

        public System.Data.IsolationLevel DefaultIsolationLevel
        {
            get
            {
                return _DefaultIsolationLevel;
            }
        }

        public System.Data.IsolationLevel GetCurrentTransactionScopeDataIsolationLevel()
        {
            return System.Data.IsolationLevel.Snapshot;
        }

        public string CommandTextSetTransactionIsolationLevel(System.Data.IsolationLevel isolationLevel)
        {
            switch (isolationLevel)
            {
                case System.Data.IsolationLevel.Unspecified:
                    throw new ArgumentOutOfRangeException();

                case System.Data.IsolationLevel.Chaos:
                    throw new ArgumentOutOfRangeException();

                case System.Data.IsolationLevel.ReadUncommitted:
                    return "SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED";

                case System.Data.IsolationLevel.ReadCommitted:
                    return "SET TRANSACTION ISOLATION LEVEL READ COMMITTED";

                case System.Data.IsolationLevel.RepeatableRead:
                    return "SET TRANSACTION ISOLATION LEVEL REPEATABLE READ";

                case System.Data.IsolationLevel.Serializable:
                    return "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE";

                case System.Data.IsolationLevel.Snapshot:
                    return "SET TRANSACTION ISOLATION LEVEL SNAPSHOT";

                default:
                    throw new ArgumentOutOfRangeException();
            }
        }

        public System.Data.IsolationLevel GetDbCurrentSessionTransactionIsolationLevel()
        {
            var result = this.Database.SqlQuery<short>(CommandTextGetTransactionIsolationLevel).FirstOrDefault();
            switch (result)
            {
                case 5:
                    return IsolationLevel.Snapshot;

                case 4:
                    return IsolationLevel.Serializable;

                case 3:
                    return IsolationLevel.RepeatableRead;

                case 2:
                    return IsolationLevel.ReadCommitted;

                case 1:
                    return IsolationLevel.ReadUncommitted;

                default:
                    return IsolationLevel.Unspecified;
            }
        }
    }
}
