//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncSpotInventory
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public string AccountingEntity { get; set; }
        public string Corporation { get; set; }
        public string Currency { get; set; }
        public string Commodity { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string Unit { get; set; }
    }
}
