//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncContractDetail
    {
        public long Id { get; set; }
        public bool Unavailable { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public int ContractDetailId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public string Material { get; set; }
        public string Brand { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> BasisPrice { get; set; }
        public Nullable<decimal> SettlementPrice { get; set; }
        public Nullable<decimal> PremiumDiscount { get; set; }
        public Nullable<decimal> FreightCharges { get; set; }
        public Nullable<decimal> ProcessingCharges { get; set; }
        public string PremiumDiscountType { get; set; }
    }
}
