//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncSpotTrade
    {
        public long Id { get; set; }
        public byte RecordStatus { get; set; }
        public Nullable<int> AccountingDataLogId { get; set; }
        public string OriginalId { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public string AccountingEntity { get; set; }
        public string Sponsor { get; set; }
        public string TradingPurpose { get; set; }
        public string Currency { get; set; }
        public string Commodity { get; set; }
        public string Direction { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ExtensionFee { get; set; }
        public Nullable<decimal> Rebate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Corporation { get; set; }
        public string HedgingCorporation { get; set; }
        public Nullable<decimal> PremiumDiscount { get; set; }
        public string Counterparty { get; set; }
        public string Brand { get; set; }
        public string Warehouse { get; set; }
        public Nullable<decimal> OtherFees { get; set; }
        public string PaymentMethods { get; set; }
        public string ContractNumber { get; set; }
        public string ContractCommodity { get; set; }
        public Nullable<decimal> ContractVolume { get; set; }
        public string Operator { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ContractId { get; set; }
        public string DataType { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<System.DateTime> LastProcessingTime { get; set; }
        public Nullable<System.DateTime> LastUserModifiesTime { get; set; }
        public bool Unavailable { get; set; }
        public string ContractType { get; set; }
    }
}
