//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TpProject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TpProject()
        {
            this.TpProjectImplementation = new HashSet<TpProjectImplementation>();
        }
    
        public int TpProjectId { get; set; }
        public bool IsDeleted { get; set; }
        public string ProjectNumber { get; set; }
        public Nullable<int> ProjectType { get; set; }
        public Nullable<int> ProjectStatus { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> CargoUnitId { get; set; }
        public Nullable<decimal> CargoQuantity { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public Nullable<int> OurCorporationId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TpProjectImplementation> TpProjectImplementation { get; set; }
    }
}
