//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFAccountingFee
    {
        public int WFAccountingFeeId { get; set; }
        public Nullable<System.DateTime> FeeDate { get; set; }
        public Nullable<System.DateTime> FinanceDate { get; set; }
        public string AccountEntity { get; set; }
        public string Coporation { get; set; }
        public string Commodity { get; set; }
        public string FeeType { get; set; }
        public string FinanceAccount { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public string ContractCode { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string OperationType { get; set; }
        public string OperationStatus { get; set; }
    }
}
