//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFActualApprovalWF
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFActualApprovalWF()
        {
            this.WFActualApprovalStep = new HashSet<WFActualApprovalStep>();
            this.WFApprovalAttachment = new HashSet<WFApprovalAttachment>();
        }
    
        public int WFActualApprovalWFId { get; set; }
        public Nullable<int> WFApprovalWorkflowTemplateId { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<int> CurrentStepId { get; set; }
        public short ContentType { get; set; }
        public bool IsOtherForm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFActualApprovalStep> WFActualApprovalStep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFApprovalAttachment> WFApprovalAttachment { get; set; }
    }
}
