//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFAccountingDataLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFAccountingDataLog()
        {
            this.WFAccountingDataLogDetail = new HashSet<WFAccountingDataLogDetail>();
        }
    
        public int AccountingDataLogId { get; set; }
        public System.DateTime TradeDate { get; set; }
        public string AccountingEntity { get; set; }
        public string Sponsor { get; set; }
        public string Currency { get; set; }
        public string Commodity { get; set; }
        public string Direction { get; set; }
        public decimal Volume { get; set; }
        public decimal Price { get; set; }
        public string Corporation { get; set; }
        public string Counterparty { get; set; }
        public string Brand { get; set; }
        public string Warehouse { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int OperationType { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public string LinkId { get; set; }
        public string DataType { get; set; }
        public string Modifier { get; set; }
        public int ContractId { get; set; }
        public string Note { get; set; }
        public Nullable<byte> ProcessingStatus { get; set; }
        public Nullable<decimal> PremiumDiscount { get; set; }
        public string ContractCode { get; set; }
        public string ContractType { get; set; }
        public Nullable<decimal> ExtensionFee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFAccountingDataLogDetail> WFAccountingDataLogDetail { get; set; }
    }
}
