//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFAmountRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFAmountRecord()
        {
            this.WFAmountRecordDetail = new HashSet<WFAmountRecordDetail>();
        }
    
        public int WFAmountRecordId { get; set; }
        public Nullable<int> WFPayRequestId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public bool IsPay { get; set; }
        public Nullable<int> PayType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public bool IsSystemGenerate { get; set; }
        public string Note { get; set; }
        public Nullable<int> CompanyBankInfoId { get; set; }
        public bool IsDeleted { get; set; }
        public string PayPurpose { get; set; }
        public Nullable<int> WFSettlementRequestId { get; set; }
        public Nullable<System.DateTime> PayReceiveDate { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<int> SalerId { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public short PayPurposeType { get; set; }
        public Nullable<decimal> MarginReturned { get; set; }
        public Nullable<decimal> MarginAsPayment { get; set; }
        public short TradeType { get; set; }
        public Nullable<int> ExchangeRateId { get; set; }
        public Nullable<int> ActualCurrencyId { get; set; }
        public Nullable<decimal> ActualCurrencyAmount { get; set; }
        public Nullable<decimal> SettleCurrencyPresentValue { get; set; }
        public Nullable<decimal> SettleCurrencyFutureValue { get; set; }
        public Nullable<decimal> ActualCurrencyPresentValue { get; set; }
        public Nullable<decimal> ActualCurrencyFutureValue { get; set; }
        public Nullable<int> WFExchangeBillId { get; set; }
        public Nullable<decimal> BillDiscountRate { get; set; }
        public Nullable<int> BillDiscountDays { get; set; }
        public int DetailObjectType { get; set; }
        public Nullable<System.Guid> WholeAmountUid { get; set; }
        public Nullable<int> AnnualDays { get; set; }
        public Nullable<decimal> DiscountRatio { get; set; }
        public int AmountMapType { get; set; }
        public Nullable<int> AmountPayeeId { get; set; }
        public Nullable<int> WFReceivingClaimId { get; set; }
        public string ExchangeBillCode { get; set; }
        public Nullable<int> WFPaymentProposalId { get; set; }
    
        public virtual WFReceivingClaim WFReceivingClaim { get; set; }
        public virtual WFExchangeBill WFExchangeBill { get; set; }
        public virtual WFPaymentProposal WFPaymentProposal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFAmountRecordDetail> WFAmountRecordDetail { get; set; }
        public virtual WFPayRequest WFPayRequest { get; set; }
    }
}
