//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFApprovalWorkflowLog
    {
        public int WFApprovalWorkflowLogId { get; set; }
        public Nullable<int> ActualApprovalWFId { get; set; }
        public Nullable<int> WFActualApprovalStepId { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Note { get; set; }
        public Nullable<int> ApprovalAction { get; set; }
        public Nullable<short> Result { get; set; }
        public Nullable<int> Receiver { get; set; }
        public Nullable<int> PreviousActionId { get; set; }
    
        public virtual WFActualApprovalStep WFActualApprovalStep { get; set; }
    }
}
