//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFApprovalAttachment
    {
        public int WFApprovalAttachmentId { get; set; }
        public Nullable<int> WFActualApprovalWFId { get; set; }
        public Nullable<int> AttachmentId { get; set; }
        public Nullable<bool> IsMainContent { get; set; }
    
        public virtual WFActualApprovalWF WFActualApprovalWF { get; set; }
    }
}
