//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFBillTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFBillTemplate()
        {
            this.WFBillContentArchive = new HashSet<WFBillContentArchive>();
            this.WFBusinessBillTemplate = new HashSet<WFBusinessBillTemplate>();
        }
    
        public int WFBillTemplateId { get; set; }
        public string Name { get; set; }
        public string HTMLContent { get; set; }
        public string Note { get; set; }
        public int TemplateType { get; set; }
        public bool IsDeleted { get; set; }
        public string TemplateFile { get; set; }
        public int TemplateFileType { get; set; }
        public Nullable<int> PrintCountCap { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFBillContentArchive> WFBillContentArchive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFBusinessBillTemplate> WFBusinessBillTemplate { get; set; }
    }
}
