//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFBillContentArchive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFBillContentArchive()
        {
            this.WFBillContentPrint = new HashSet<WFBillContentPrint>();
        }
    
        public int WFBillContentArchiveId { get; set; }
        public int BillType { get; set; }
        public string BillContent { get; set; }
        public Nullable<int> BillId { get; set; }
        public short BillContentType { get; set; }
        public Nullable<int> WFBillTemplateId { get; set; }
        public Nullable<System.DateTime> LastManipulateTime { get; set; }
    
        public virtual WFBillTemplate WFBillTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFBillContentPrint> WFBillContentPrint { get; set; }
    }
}
