//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFBuyContractTradeRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFBuyContractTradeRecord()
        {
            this.WFCostPrice = new HashSet<WFCostPrice>();
        }
    
        public int WFBuyContractTradeRecordId { get; set; }
        public Nullable<int> WFContractEntryRecordDetailId { get; set; }
        public Nullable<int> WFContractDetailInfoId { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public int UnitId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int CurrencyId { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<decimal> PremiumDiscount { get; set; }
        public Nullable<int> WFFirePriceRecordId { get; set; }
        public Nullable<int> WFFinalPriceId { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public Nullable<int> ComponentCargoUnitId { get; set; }
        public Nullable<decimal> ComponentCargoQuantity { get; set; }
    
        public virtual WFContractEntryRecordDetail WFContractEntryRecordDetail { get; set; }
        public virtual WFContractDetailInfo WFContractDetailInfo { get; set; }
        public virtual WFFinalPrice WFFinalPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCostPrice> WFCostPrice { get; set; }
    }
}
