//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCardCodeInfo
    {
        public int WFCardCodeInfoId { get; set; }
        public int WarehouseId { get; set; }
        public int UserId { get; set; }
        public int CorporationId { get; set; }
        public string CardCode { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool Used { get; set; }
        public string Note { get; set; }
    }
}
