//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCarry
    {
        public int WFCarryId { get; set; }
        public int ToObjectId { get; set; }
        public int ToObjectType { get; set; }
        public decimal ToAmount { get; set; }
        public int ToCurrencyId { get; set; }
        public int FromObjectId { get; set; }
        public int FromObjectType { get; set; }
        public decimal FromAmount { get; set; }
        public int FromCurrencyId { get; set; }
        public Nullable<int> ExchangeRateId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> Creator { get; set; }
        public string Notes { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CarryDate { get; set; }
    }
}
