//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCorporationTypeConfiguration
    {
        public int WFCorporationTypeConfigurationId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> WFCompanyId { get; set; }
        public Nullable<int> CorporationType { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<decimal> PledgeInterestRate { get; set; }
        public Nullable<decimal> PledgeProportion { get; set; }
        public Nullable<int> ExchangeTypeId { get; set; }
        public string TimeZoneId { get; set; }
    
        public virtual WFCompany WFCompany { get; set; }
    }
}
