//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFContractDetailInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFContractDetailInfo()
        {
            this.WFBuyContractTradeRecord = new HashSet<WFBuyContractTradeRecord>();
            this.WFContractDetailQuantity = new HashSet<WFContractDetailQuantity>();
            this.WFContractEntryRecordDetail = new HashSet<WFContractEntryRecordDetail>();
            this.WFContractOutRecordDetail = new HashSet<WFContractOutRecordDetail>();
            this.WFContractInvoice = new HashSet<WFContractInvoice>();
            this.WFInvoiceRequestDetail = new HashSet<WFInvoiceRequestDetail>();
        }
    
        public int WFContractDetailInfoId { get; set; }
        public Nullable<int> WFContractInfoId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> SpecificationId { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ActualPrice { get; set; }
        public Nullable<decimal> PremiumDiscount { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public Nullable<decimal> CommodityHappened { get; set; }
        public bool IsSpot { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> ExposureVolumne { get; set; }
        public Nullable<decimal> BasicGap { get; set; }
        public Nullable<System.Guid> WholeContractDetailUid { get; set; }
        public Nullable<int> WFPriceInfoId { get; set; }
        public Nullable<decimal> CommodityApplied { get; set; }
        public Nullable<int> DeliveryWarehouseId { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFBuyContractTradeRecord> WFBuyContractTradeRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractDetailQuantity> WFContractDetailQuantity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractEntryRecordDetail> WFContractEntryRecordDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractOutRecordDetail> WFContractOutRecordDetail { get; set; }
        public virtual WFPriceInfo WFPriceInfo { get; set; }
        public virtual WFContractInfo WFContractInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractInvoice> WFContractInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFInvoiceRequestDetail> WFInvoiceRequestDetail { get; set; }
    }
}
