//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFContractBillArchive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFContractBillArchive()
        {
            this.WFContractBillArchiveDetail = new HashSet<WFContractBillArchiveDetail>();
            this.WFContractBillArchiveLinker = new HashSet<WFContractBillArchiveLinker>();
        }
    
        public int WFContractBillArchiveId { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> RelatedObjectId { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<short> ApprovalStatus { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> Saler { get; set; }
        public short BillType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractBillArchiveDetail> WFContractBillArchiveDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractBillArchiveLinker> WFContractBillArchiveLinker { get; set; }
    }
}
