//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFContact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFContact()
        {
            this.WFContactCommodityAccountEntity = new HashSet<WFContactCommodityAccountEntity>();
        }
    
        public int WFContactId { get; set; }
        public Nullable<int> WFCompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public string OpenBillAddress { get; set; }
        public string OpenBillTelphone { get; set; }
        public string LinkMan { get; set; }
        public string LinkPhone { get; set; }
        public string MobilePhone { get; set; }
        public string PostCode { get; set; }
        public string MailingAddress { get; set; }
        public string Note { get; set; }
        public string Fax { get; set; }
        public string IdCode { get; set; }
        public string CarCode { get; set; }
        public string ContactEnglishName { get; set; }
        public string EnglishAddress { get; set; }
    
        public virtual WFCompany WFCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContactCommodityAccountEntity> WFContactCommodityAccountEntity { get; set; }
    }
}
