//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCodeTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFCodeTemplate()
        {
            this.WFCodeTemplateDetail = new HashSet<WFCodeTemplateDetail>();
            this.WFSystemCodeInfo = new HashSet<WFSystemCodeInfo>();
        }
    
        public int WFCodeTemplateId { get; set; }
        public string TemplateName { get; set; }
        public Nullable<int> MaxGenLen { get; set; }
        public Nullable<int> MinGenLen { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCodeTemplateDetail> WFCodeTemplateDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSystemCodeInfo> WFSystemCodeInfo { get; set; }
    }
}
