//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCorporationApprovalWFTemplate
    {
        public int WFCorporationApprovalWFTemplateId { get; set; }
        public Nullable<int> WFCompanyId { get; set; }
        public int WFApprovalWorkflowTemplateId { get; set; }
        public int ApprovalType { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> BusinessDepartmentId { get; set; }
        public Nullable<int> RequestDepartmentId { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> WFConditionId { get; set; }
        public Nullable<int> TradeType { get; set; }
        public int Priority { get; set; }
    
        public virtual WFApprovalWorkflowTemplate WFApprovalWorkflowTemplate { get; set; }
        public virtual WFCompany WFCompany { get; set; }
        public virtual WFCondition WFCondition { get; set; }
    }
}
