//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFComponentVariety
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFComponentVariety()
        {
            this.WFCommodityQuantityUnit = new HashSet<WFCommodityQuantityUnit>();
        }
    
        public int WFComponentVarietyId { get; set; }
        public Nullable<int> WFCommodityId { get; set; }
        public Nullable<int> PricingVarietyId { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> FundamentalVarietyId { get; set; }
        public Nullable<int> ComponentCategory { get; set; }
        public Nullable<int> MainQuantityId { get; set; }
    
        public virtual WFCommodity WFCommodity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCommodityQuantityUnit> WFCommodityQuantityUnit { get; set; }
    }
}
