//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFContractInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFContractInvoice()
        {
            this.WFInvoiceDetailQuantity = new HashSet<WFInvoiceDetailQuantity>();
            this.WFInvoiceObject = new HashSet<WFInvoiceObject>();
        }
    
        public int WFContractInvoiceId { get; set; }
        public Nullable<int> WFInvoiceRecordId { get; set; }
        public Nullable<int> WFContractDetailInfoId { get; set; }
        public Nullable<int> SpecificationId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Note { get; set; }
        public bool IsFinished { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> Taxation { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> HappendAmount { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<int> Bundles { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public Nullable<decimal> FinalWeight { get; set; }
        public Nullable<System.Guid> WholeInvoiceDetailUid { get; set; }
        public Nullable<decimal> FinalAmount { get; set; }
    
        public virtual WFContractDetailInfo WFContractDetailInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFInvoiceDetailQuantity> WFInvoiceDetailQuantity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFInvoiceObject> WFInvoiceObject { get; set; }
        public virtual WFInvoiceRecord WFInvoiceRecord { get; set; }
    }
}
