//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFContractInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFContractInfo()
        {
            this.WFAmountRecordDetail = new HashSet<WFAmountRecordDetail>();
            this.WFCommercialInvoice = new HashSet<WFCommercialInvoice>();
            this.WFContractBillArchiveLinker = new HashSet<WFContractBillArchiveLinker>();
            this.WFContractComment = new HashSet<WFContractComment>();
            this.WFContractComponent = new HashSet<WFContractComponent>();
            this.WFContractCustomer = new HashSet<WFContractCustomer>();
            this.WFContractDetailInfo = new HashSet<WFContractDetailInfo>();
            this.WFContractFee = new HashSet<WFContractFee>();
            this.WFContractLog = new HashSet<WFContractLog>();
            this.WFLcContract = new HashSet<WFLcContract>();
            this.WFPaymentProposalDetail = new HashSet<WFPaymentProposalDetail>();
            this.WFPriceConfirmationLetter = new HashSet<WFPriceConfirmationLetter>();
            this.WFSupplementalAgreement = new HashSet<WFSupplementalAgreement>();
            this.WFOrderInfo = new HashSet<WFOrderInfo>();
            this.WFPayRequestDetail = new HashSet<WFPayRequestDetail>();
            this.WFSettlementRequestDetail = new HashSet<WFSettlementRequestDetail>();
        }
    
        public int WFContractInfoId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public bool IsBuy { get; set; }
        public Nullable<int> ContractType { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> SalerId { get; set; }
        public Nullable<int> ExcutorId { get; set; }
        public Nullable<decimal> AmountTotal { get; set; }
        public Nullable<decimal> AmountActualTotal { get; set; }
        public string ContractCode { get; set; }
        public Nullable<int> WFLongContractId { get; set; }
        public Nullable<int> WFDeliveryContractId { get; set; }
        public Nullable<int> WFLongContractDetailId { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> StatusOfAmount { get; set; }
        public Nullable<int> StatusOfCommodity { get; set; }
        public Nullable<int> StatusOfInvoice { get; set; }
        public Nullable<decimal> AmountHappened { get; set; }
        public Nullable<decimal> CommodityHappened { get; set; }
        public Nullable<decimal> InvoiceHappened { get; set; }
        public Nullable<int> StatusOfContract { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
        public Nullable<int> Modifier { get; set; }
        public int UnitId { get; set; }
        public int CurrencyId { get; set; }
        public bool IsDeleted { get; set; }
        public string TradingPurpose { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public bool NeedPayTransferFee { get; set; }
        public Nullable<short> DeliveryType { get; set; }
        public Nullable<short> ApprovalStatus { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public short TransactionType { get; set; }
        public Nullable<int> WFContractWholeId { get; set; }
        public Nullable<int> TransactionSetting { get; set; }
        public int AccountPeriod { get; set; }
        public short TradeType { get; set; }
        public Nullable<int> WFPriceInfoId { get; set; }
        public Nullable<int> PriceMakingType { get; set; }
        public Nullable<int> WFSettleOptionId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<short> TradePattern { get; set; }
        public bool IsAmountIncludeDiscountCost { get; set; }
        public Nullable<decimal> DiscountCost { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> ApplyingPaymentAmount { get; set; }
        public Nullable<decimal> InvoiceApplied { get; set; }
        public Nullable<int> CompanyBankInfoId { get; set; }
        public bool IsSystemGenerate { get; set; }
        public int ContractMapType { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> CommodityApplied { get; set; }
        public Nullable<int> SapConfTaxCodeId { get; set; }
        public Nullable<System.DateTime> InvoiceCompletedDate { get; set; }
        public Nullable<System.DateTime> CommodityCompletedDate { get; set; }
        public Nullable<System.DateTime> PriceCompletedDate { get; set; }
        public Nullable<System.DateTime> AmountCompletedDate { get; set; }
        public Nullable<System.DateTime> ContractCompletedDate { get; set; }
        public Nullable<int> SpecialTradeType { get; set; }
        public Nullable<decimal> PriceToleranceRatio { get; set; }
        public Nullable<decimal> CargoToleranceRatio { get; set; }
        public Nullable<int> CargoPriceMatchStatus { get; set; }
        public bool IsAllPriceCompleted { get; set; }
        public Nullable<decimal> MoneyCargoToleranceAmount { get; set; }
        public bool IsReturn { get; set; }
        public bool IsPurchase { get; set; }
        public int Direction { get; set; }
        public Nullable<int> PurposeType { get; set; }
        public Nullable<bool> IsSealed { get; set; }
        public Nullable<System.DateTime> AgreementDate { get; set; }
        public Nullable<decimal> CargoQuantityTolerance { get; set; }
        public Nullable<int> DefaultSrcLogisticsPlaceId { get; set; }
        public Nullable<int> DefaultDstLogisticsPlaceId { get; set; }
        public Nullable<int> DefaultVehicleTransportSpecId { get; set; }
        public Nullable<int> DefaultLogisticsCompanyId { get; set; }
        public Nullable<int> TradingStrategyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFAmountRecordDetail> WFAmountRecordDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCommercialInvoice> WFCommercialInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractBillArchiveLinker> WFContractBillArchiveLinker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractComment> WFContractComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractComponent> WFContractComponent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractCustomer> WFContractCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractDetailInfo> WFContractDetailInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractFee> WFContractFee { get; set; }
        public virtual WFContractWhole WFContractWhole { get; set; }
        public virtual WFPriceInfo WFPriceInfo { get; set; }
        public virtual WFContractSecondPart WFContractSecondPart { get; set; }
        public virtual WFLongContract WFLongContract { get; set; }
        public virtual WFDeliveryContract WFDeliveryContract { get; set; }
        public virtual WFLongContractDetail WFLongContractDetail { get; set; }
        public virtual WFSettleOption WFSettleOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractLog> WFContractLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFLcContract> WFLcContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPaymentProposalDetail> WFPaymentProposalDetail { get; set; }
        public virtual WFPledgeContract WFPledgeContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPriceConfirmationLetter> WFPriceConfirmationLetter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSupplementalAgreement> WFSupplementalAgreement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFOrderInfo> WFOrderInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPayRequestDetail> WFPayRequestDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSettlementRequestDetail> WFSettlementRequestDetail { get; set; }
    }
}
