//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCompanyBankInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFCompanyBankInfo()
        {
            this.WFCompanyBankInfoCommodityAccountEntity = new HashSet<WFCompanyBankInfoCommodityAccountEntity>();
        }
    
        public int WFCompanyBankInfoId { get; set; }
        public Nullable<int> WFCompanyId { get; set; }
        public string BankName { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Address { get; set; }
        public bool IsDeleted { get; set; }
        public string EnglishName { get; set; }
        public Nullable<int> LegacyWarehouseBankInfoId { get; set; }
        public string SwiftCode { get; set; }
        public bool IsDisabled { get; set; }
        public string SAPCode { get; set; }
    
        public virtual WFCompany WFCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCompanyBankInfoCommodityAccountEntity> WFCompanyBankInfoCommodityAccountEntity { get; set; }
    }
}
