//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCondition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFCondition()
        {
            this.WFApprovalConfiguration = new HashSet<WFApprovalConfiguration>();
            this.WFBusinessBillTemplate = new HashSet<WFBusinessBillTemplate>();
            this.WFCorporationApprovalWFTemplate = new HashSet<WFCorporationApprovalWFTemplate>();
            this.WFStepConditionTemplate = new HashSet<WFStepConditionTemplate>();
        }
    
        public int WFConditionId { get; set; }
        public string Name { get; set; }
        public int ConditionType { get; set; }
        public int EvaluationType { get; set; }
        public string Expression { get; set; }
        public string Note { get; set; }
        public Nullable<int> ApprovalType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFApprovalConfiguration> WFApprovalConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFBusinessBillTemplate> WFBusinessBillTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCorporationApprovalWFTemplate> WFCorporationApprovalWFTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFStepConditionTemplate> WFStepConditionTemplate { get; set; }
    }
}
