//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFCompany()
        {
            this.WFBusiness = new HashSet<WFBusiness>();
            this.WFCompanyBusiness = new HashSet<WFCompanyBusiness>();
            this.WFCompany1 = new HashSet<WFCompany>();
            this.WFCompanySAPCode = new HashSet<WFCompanySAPCode>();
            this.WFContact = new HashSet<WFContact>();
            this.WFCorporationApprovalWFTemplate = new HashSet<WFCorporationApprovalWFTemplate>();
            this.WFCorporationTypeConfiguration = new HashSet<WFCorporationTypeConfiguration>();
            this.WFCustomerCommodity = new HashSet<WFCustomerCommodity>();
            this.WFInstrument = new HashSet<WFInstrument>();
            this.WFInstrumentCategory = new HashSet<WFInstrumentCategory>();
            this.WFCompanyBankInfo = new HashSet<WFCompanyBankInfo>();
        }
    
        public int WFCompanyId { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string LegalRepresentative { get; set; }
        public string NatureText { get; set; }
        public Nullable<System.DateTime> FoundDate { get; set; }
        public string Telphone { get; set; }
        public string Fax { get; set; }
        public string TaxCode { get; set; }
        public string OpenBillAddress { get; set; }
        public string OpenBillTelphone { get; set; }
        public string MailingAddress { get; set; }
        public string PostCode { get; set; }
        public string LinkMan { get; set; }
        public string LinkPhone { get; set; }
        public string MobilePhone { get; set; }
        public string Note { get; set; }
        public Nullable<int> Type { get; set; }
        public bool IsDeleted { get; set; }
        public string Abbreviation { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<short> CreditRatingModificationStatus { get; set; }
        public Nullable<int> BuyWFCreditRatingId { get; set; }
        public Nullable<int> SaleWFCreditRatingId { get; set; }
        public Nullable<int> CorporationRank { get; set; }
        public string EnglishFullName { get; set; }
        public string EnglishShortName { get; set; }
        public string EnglishOpenBillAddress { get; set; }
        public string EnglishMailingAddress { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<decimal> RegistCapital { get; set; }
        public Nullable<int> RegisteredCapitalCurrencyId { get; set; }
        public Nullable<bool> IsDomestic { get; set; }
        public int LockSettings { get; set; }
        public Nullable<int> MetaCompanyType { get; set; }
        public Nullable<int> RelationCategory { get; set; }
        public string AccountingName { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastManipulationTime { get; set; }
        public Nullable<int> OurCorporationFunctionalCurrencyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFBusiness> WFBusiness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCompanyBusiness> WFCompanyBusiness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCompany> WFCompany1 { get; set; }
        public virtual WFCompany WFCompany2 { get; set; }
        public virtual WFCreditRating WFCreditRating { get; set; }
        public virtual WFCreditRating WFCreditRating1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCompanySAPCode> WFCompanySAPCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContact> WFContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCorporationApprovalWFTemplate> WFCorporationApprovalWFTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCorporationTypeConfiguration> WFCorporationTypeConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCustomerCommodity> WFCustomerCommodity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFInstrument> WFInstrument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFInstrumentCategory> WFInstrumentCategory { get; set; }
        public virtual WFWarehouseCompany WFWarehouseCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCompanyBankInfo> WFCompanyBankInfo { get; set; }
    }
}
