//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCodeTemplateDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFCodeTemplateDetail()
        {
            this.WFCodeCustomization = new HashSet<WFCodeCustomization>();
        }
    
        public int WFCodeTemplateDetailId { get; set; }
        public int WFCodeTemplateId { get; set; }
        public int OrderIndex { get; set; }
        public int EvalExp { get; set; }
        public string ConstValue { get; set; }
        public string FormatString { get; set; }
        public Nullable<int> MaxGenLen { get; set; }
        public Nullable<int> MinGenLen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCodeCustomization> WFCodeCustomization { get; set; }
        public virtual WFCodeTemplate WFCodeTemplate { get; set; }
    }
}
