//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCostPayRecord
    {
        public int WFCostPayRecordId { get; set; }
        public Nullable<int> WFCostPayRequestId { get; set; }
        public int CorporationId { get; set; }
        public int CustomerId { get; set; }
        public int PayType { get; set; }
        public decimal Amount { get; set; }
        public int CurrencyId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Note { get; set; }
        public int CompanyBankInfoId { get; set; }
        public bool IsDeleted { get; set; }
        public string PayPurpose { get; set; }
        public System.DateTime PayReceiveDate { get; set; }
        public int CommodityId { get; set; }
        public Nullable<int> Creator { get; set; }
        public int AccountingEntityId { get; set; }
        public int CostType { get; set; }
        public Nullable<System.DateTime> LastModifyDate { get; set; }
        public short TradeType { get; set; }
    
        public virtual WFCostPayRequest WFCostPayRequest { get; set; }
    }
}
