//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFDateVaryingPropertyConf
    {
        public int WFDateVaryingPropertyConfId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastManipulationTime { get; set; }
        public Nullable<int> LastManipulatorId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> EntityId { get; set; }
        public Nullable<int> EntityType { get; set; }
        public Nullable<int> Property { get; set; }
        public string PropertyValue { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
