//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFDeliveryNotificationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFDeliveryNotificationDetail()
        {
            this.WFDeliveryNotificationObject = new HashSet<WFDeliveryNotificationObject>();
        }
    
        public int WFDeliveryNotificationDetailId { get; set; }
        public Nullable<int> WFDeliveryNotificationId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> SpecificationId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string SAPCode { get; set; }
        public string GroupCode { get; set; }
        public string StorageCode { get; set; }
        public Nullable<System.Guid> WholeDeliveryNotificationDetailUid { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Notes { get; set; }
    
        public virtual WFDeliveryNotification WFDeliveryNotification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFDeliveryNotificationObject> WFDeliveryNotificationObject { get; set; }
    }
}
