//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFFirePricePostponeConfirm
    {
        public int WFFirePricePostponeConfirmId { get; set; }
        public Nullable<System.DateTime> FromLastPricingDate { get; set; }
        public Nullable<System.DateTime> ToLastPricingDate { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public Nullable<int> FromInstrument { get; set; }
        public Nullable<int> ToInstrument { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<short> ApprovalStatus { get; set; }
        public string Code { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<int> WFPriceDetailId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual WFPriceDetail WFPriceDetail { get; set; }
    }
}
