//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFFirePriceRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFFirePriceRecord()
        {
            this.WFTradePricing = new HashSet<WFTradePricing>();
        }
    
        public int WFFirePriceRecordId { get; set; }
        public Nullable<int> WFFirePriceConfirmId { get; set; }
        public Nullable<System.DateTime> FireDate { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
        public int UnitId { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<int> InstrumentId { get; set; }
        public string Note { get; set; }
        public bool IsConfirmed { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> PremiumDiscount { get; set; }
        public Nullable<decimal> SettlementPrice { get; set; }
        public bool IsDefered { get; set; }
        public Nullable<decimal> DeferedFee { get; set; }
        public Nullable<int> MarketId { get; set; }
        public Nullable<decimal> HappenedMargin { get; set; }
        public Nullable<int> WFPriceDetailId { get; set; }
        public Nullable<decimal> SwapFee { get; set; }
        public short PricingType { get; set; }
        public Nullable<int> MarketQuoteId { get; set; }
        public int CargoUnitId { get; set; }
        public Nullable<System.DateTime> LastManipulateTime { get; set; }
        public Nullable<decimal> PricingCargoQuantity { get; set; }
        public bool IsUnpriced { get; set; }
        public Nullable<int> MarketQuotePriceType { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> SalerId { get; set; }
    
        public virtual WFFirePriceConfirm WFFirePriceConfirm { get; set; }
        public virtual WFPriceDetail WFPriceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFTradePricing> WFTradePricing { get; set; }
    }
}
