//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFFinalPrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFFinalPrice()
        {
            this.WFBuyContractTradeRecord = new HashSet<WFBuyContractTradeRecord>();
            this.WFSaleContractTradeRecord = new HashSet<WFSaleContractTradeRecord>();
        }
    
        public int WFFinalPriceId { get; set; }
        public Nullable<int> WFPriceDetailId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> FinalExchangeRateId { get; set; }
        public Nullable<decimal> PricingFinalPrice { get; set; }
        public Nullable<decimal> PricingFinalPremiumDiscount { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public Nullable<decimal> FinalPremiumDiscount { get; set; }
        public bool IsAdjusted { get; set; }
        public Nullable<System.DateTime> ExchangeRateConfirmDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFBuyContractTradeRecord> WFBuyContractTradeRecord { get; set; }
        public virtual WFPriceDetail WFPriceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSaleContractTradeRecord> WFSaleContractTradeRecord { get; set; }
    }
}
