//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFFinancialBatch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFFinancialBatch()
        {
            this.WFFinancialBatch1 = new HashSet<WFFinancialBatch>();
            this.WFFinancialBatchInventory = new HashSet<WFFinancialBatchInventory>();
            this.WFFinancialBatchOutDetail = new HashSet<WFFinancialBatchOutDetail>();
            this.WFMultiPrecursorBatch = new HashSet<WFMultiPrecursorBatch>();
            this.WFMultiPrecursorBatch1 = new HashSet<WFMultiPrecursorBatch>();
            this.WFPostingInfoDetail = new HashSet<WFPostingInfoDetail>();
        }
    
        public int WFFinancialBatchId { get; set; }
        public string FinancialBatchCode { get; set; }
        public Nullable<short> CreationSystem { get; set; }
        public Nullable<int> PrecursorFinancialBatchId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> SpecificationId { get; set; }
        public Nullable<short> InventoryStorageType { get; set; }
        public Nullable<short> SavePlaceType { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> ExchangeId { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<int> WarehouseEntryRecordId { get; set; }
        public Nullable<decimal> InQuantity { get; set; }
        public Nullable<decimal> OutQuantity { get; set; }
        public Nullable<decimal> PostingWeight { get; set; }
        public Nullable<decimal> OutPostingWeight { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsCompositionPricing { get; set; }
        public Nullable<int> DeliveryInDetaiId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFFinancialBatch> WFFinancialBatch1 { get; set; }
        public virtual WFFinancialBatch WFFinancialBatch2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFFinancialBatchInventory> WFFinancialBatchInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFFinancialBatchOutDetail> WFFinancialBatchOutDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFMultiPrecursorBatch> WFMultiPrecursorBatch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFMultiPrecursorBatch> WFMultiPrecursorBatch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPostingInfoDetail> WFPostingInfoDetail { get; set; }
    }
}
