//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFFreightPrice
    {
        public int WFFreightPriceId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastManipulationTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int SrcLogisticsPlaceId { get; set; }
        public int DstLogisticsPlaceId { get; set; }
        public int VehicleTransportSpecId { get; set; }
        public int FreightPriceType { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> CargoUnitId { get; set; }
        public int LogisticsCompanyId { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
