//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFInvoiceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFInvoiceRequest()
        {
            this.WFInvoiceRecord = new HashSet<WFInvoiceRecord>();
            this.WFInvoiceRequestDetail = new HashSet<WFInvoiceRequestDetail>();
        }
    
        public int WFInvoiceRequestId { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Taxation { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RequestorId { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CustomerBankId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> SalerId { get; set; }
        public short TradeType { get; set; }
        public int UnitId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFInvoiceRecord> WFInvoiceRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFInvoiceRequestDetail> WFInvoiceRequestDetail { get; set; }
    }
}
