//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFInvoiceRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFInvoiceRecord()
        {
            this.WFContractInvoice = new HashSet<WFContractInvoice>();
            this.WFInvoiceObject = new HashSet<WFInvoiceObject>();
            this.WFInvoiceRecord1 = new HashSet<WFInvoiceRecord>();
        }
    
        public int WFInvoiceRecordId { get; set; }
        public Nullable<int> WFInvoiceRequestId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public bool IsReceive { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<int> ExpressageCompaniesId { get; set; }
        public string ExpressNumber { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<int> SalerId { get; set; }
        public short TradeType { get; set; }
        public short InvoiceType { get; set; }
        public int CurrencyId { get; set; }
        public int UnitId { get; set; }
        public string InvoiceCode { get; set; }
        public Nullable<int> ExchangeProcessType { get; set; }
        public Nullable<int> PaymentFormType { get; set; }
        public bool IsAmountIncludeDiscountCost { get; set; }
        public Nullable<decimal> DiscountCost { get; set; }
        public Nullable<System.Guid> WholeInvoiceUid { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public Nullable<int> DiscountDays { get; set; }
        public Nullable<int> AnnualDays { get; set; }
        public Nullable<decimal> DiscountRatio { get; set; }
        public Nullable<int> AmountPayeeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> Status { get; set; }
        public string ReverseDocumentSAPCode { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<decimal> Taxation { get; set; }
        public Nullable<int> CustomerBankId { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> BusinessInvoiceId { get; set; }
        public Nullable<int> InvoiceCategory { get; set; }
        public Nullable<int> AdjustInvoiceType { get; set; }
        public Nullable<int> InvoicePropertyType { get; set; }
        public string TaxInvoiceCode { get; set; }
        public string TaxInvoiceNumber { get; set; }
        public Nullable<bool> IsReturn { get; set; }
    
        public virtual WFCommercialInvoice WFCommercialInvoice { get; set; }
        public virtual WFCommercialInvoice WFCommercialInvoice1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractInvoice> WFContractInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFInvoiceObject> WFInvoiceObject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFInvoiceRecord> WFInvoiceRecord1 { get; set; }
        public virtual WFInvoiceRecord WFInvoiceRecord2 { get; set; }
        public virtual WFInvoiceRequest WFInvoiceRequest { get; set; }
    }
}
