//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFInventoryAdjustmentRequest
    {
        public int WFInventoryAdjustmentRequestId { get; set; }
        public int WarehouseId { get; set; }
        public int CommodityId { get; set; }
        public int CorporationId { get; set; }
        public int AccountingEntityId { get; set; }
        public int DepartmentId { get; set; }
        public int SalerId { get; set; }
        public int InventoryStorageType { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public int UnitId { get; set; }
        public int AdjustmentType { get; set; }
        public string Reason { get; set; }
        public string Note { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public bool IsDeleted { get; set; }
        public int Creator { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<decimal> HappenedWeight { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public int TradeType { get; set; }
        public Nullable<int> Category { get; set; }
    }
}
