//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFInvoiceRequestDetail
    {
        public int WFInvoiceRequestDetailId { get; set; }
        public Nullable<int> WFInvoiceRequestId { get; set; }
        public Nullable<int> WFContractDetailInfoId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> Taxation { get; set; }
        public string Note { get; set; }
    
        public virtual WFContractDetailInfo WFContractDetailInfo { get; set; }
        public virtual WFInvoiceRequest WFInvoiceRequest { get; set; }
    }
}
