//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFOurPlantTransferWarehouseNotificationDetail
    {
        public int WFOurPlantTransferWarehouseNotificationDetailId { get; set; }
        public Nullable<int> WFOurPlantTransferWarehouseNotificationId { get; set; }
        public string IssueBatchCode { get; set; }
        public string AssignedReceiveBatchCode { get; set; }
        public decimal Weight { get; set; }
    
        public virtual WFOurPlantTransferWarehouseNotification WFOurPlantTransferWarehouseNotification { get; set; }
    }
}
