//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFPayRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFPayRequest()
        {
            this.WFAmountRecord = new HashSet<WFAmountRecord>();
            this.WFPaymentProposal = new HashSet<WFPaymentProposal>();
            this.WFPayRequestDetail = new HashSet<WFPayRequestDetail>();
        }
    
        public int WFPayRequestId { get; set; }
        public Nullable<int> WFSettlementRequestlId { get; set; }
        public Nullable<int> PayCustomerId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> CompanyBankInfoId { get; set; }
        public string PayPurpose { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> RequestorId { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public Nullable<int> PayType { get; set; }
        public bool IsDeleted { get; set; }
        public string Note { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> SalerId { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public short PayPurposeType { get; set; }
        public Nullable<short> ApprovalStatus { get; set; }
        public short TradeType { get; set; }
        public Nullable<int> ExchangeRateId { get; set; }
        public Nullable<int> ActualCurrencyId { get; set; }
        public Nullable<decimal> ActualCurrencyAmount { get; set; }
        public int DetailObjectType { get; set; }
        public bool IsSystemGenerate { get; set; }
        public int AmountMapType { get; set; }
        public Nullable<int> AmountPayeeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<bool> NeedFinancePay { get; set; }
        public Nullable<int> SapAmountTransaction { get; set; }
        public string PayRequestCode { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<bool> NeedSubmitSap { get; set; }
        public Nullable<int> CargoUnitId { get; set; }
        public Nullable<decimal> CargoQuantity { get; set; }
        public Nullable<int> CapitalPlan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFAmountRecord> WFAmountRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPaymentProposal> WFPaymentProposal { get; set; }
        public virtual WFSettlementRequest WFSettlementRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPayRequestDetail> WFPayRequestDetail { get; set; }
    }
}
