//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFPaymentProposal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFPaymentProposal()
        {
            this.WFAmountRecord = new HashSet<WFAmountRecord>();
            this.WFPaymentProposalDetail = new HashSet<WFPaymentProposalDetail>();
        }
    
        public int WFPaymentProposalId { get; set; }
        public Nullable<int> WFPayRequestId { get; set; }
        public bool IsDeleted { get; set; }
        public int PaymentProposalStatus { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool IsSystemGenerate { get; set; }
        public bool NeedFinancePay { get; set; }
        public bool IsInitialPosted { get; set; }
        public int PaymentFormType { get; set; }
        public Nullable<int> PayeeId { get; set; }
        public Nullable<int> BankAccountId { get; set; }
        public Nullable<decimal> ObjectsCurrencyAmount { get; set; }
        public Nullable<decimal> ActualCurrencyAmount { get; set; }
        public Nullable<decimal> CargoQuantity { get; set; }
        public string PaymentProposalNote { get; set; }
        public string PaymentProposalCode { get; set; }
        public Nullable<int> SapAmountTransaction { get; set; }
        public short PayPurposeType { get; set; }
        public int DetailObjectType { get; set; }
        public int AmountMapType { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> ExchangeRateId { get; set; }
        public int ObjectsCurrencyId { get; set; }
        public int ActualCurrencyId { get; set; }
        public Nullable<int> CargoUnitId { get; set; }
        public Nullable<int> PayCustomerId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFAmountRecord> WFAmountRecord { get; set; }
        public virtual WFPayRequest WFPayRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPaymentProposalDetail> WFPaymentProposalDetail { get; set; }
    }
}
