//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFPledgeRenewalDetail
    {
        public int WFPledgeRenewalDetailId { get; set; }
        public Nullable<int> WFPledgeRenewalId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> SpecificationId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> RedeemPrice { get; set; }
        public Nullable<decimal> NewPledgePrice { get; set; }
        public Nullable<decimal> RedeemBasePrice { get; set; }
        public Nullable<decimal> RedeemPremiumDiscount { get; set; }
        public Nullable<decimal> NewPledgeBasePrice { get; set; }
        public Nullable<decimal> NewPledgePremiumDiscount { get; set; }
    
        public virtual WFPledgeRenewal WFPledgeRenewal { get; set; }
    }
}
