//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFPledgeRenewal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFPledgeRenewal()
        {
            this.WFPledgeRenewalDetail = new HashSet<WFPledgeRenewalDetail>();
        }
    
        public int WFPledgeRenewalId { get; set; }
        public Nullable<int> OldPledgeContractId { get; set; }
        public Nullable<int> RedeemContractId { get; set; }
        public Nullable<int> NewPledgeContractId { get; set; }
        public string RedeemContractCode { get; set; }
        public string NewPledgeContractCode { get; set; }
        public Nullable<decimal> PledgeRate { get; set; }
        public Nullable<decimal> PledgeInterestRate { get; set; }
        public Nullable<int> PledgeDays { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<short> ApprovalStatus { get; set; }
    
        public virtual WFPledgeContract WFPledgeContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPledgeRenewalDetail> WFPledgeRenewalDetail { get; set; }
    }
}
