//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFPledgeContract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFPledgeContract()
        {
            this.WFPledgeRenewal = new HashSet<WFPledgeRenewal>();
        }
    
        public int WFContractInfoId { get; set; }
        public Nullable<int> PledgeType { get; set; }
        public Nullable<decimal> PledgeRate { get; set; }
        public Nullable<decimal> PledgeInterestRate { get; set; }
        public Nullable<int> PledgeExchangeId { get; set; }
        public Nullable<int> PledgeDays { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual WFContractInfo WFContractInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPledgeRenewal> WFPledgeRenewal { get; set; }
    }
}
