//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFPriceDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFPriceDetail()
        {
            this.WFFinalPrice = new HashSet<WFFinalPrice>();
            this.WFFirePriceConfirm = new HashSet<WFFirePriceConfirm>();
            this.WFFirePricePostponeConfirm = new HashSet<WFFirePricePostponeConfirm>();
            this.WFFirePriceRecord = new HashSet<WFFirePriceRecord>();
            this.WFPriceInstrument = new HashSet<WFPriceInstrument>();
        }
    
        public int WFPriceDetailId { get; set; }
        public Nullable<int> WFPriceInfoId { get; set; }
        public bool IsDeleted { get; set; }
        public int PriceMakingType { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> TempPrice { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<decimal> PricingTempPrice { get; set; }
        public Nullable<decimal> PricingTempPremiumDiscount { get; set; }
        public Nullable<decimal> TempPremiumDiscount { get; set; }
        public Nullable<int> PriceMarket { get; set; }
        public Nullable<int> InstrumentCategoryId { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> PricingVarietyId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<short> Scale { get; set; }
        public Nullable<int> PricingUnitId { get; set; }
        public Nullable<int> PricingCurrencyId { get; set; }
        public Nullable<short> PricingScale { get; set; }
        public Nullable<int> TempExchangeRateId { get; set; }
    
        public virtual WFAvgPriceDetail WFAvgPriceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFFinalPrice> WFFinalPrice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFFirePriceConfirm> WFFirePriceConfirm { get; set; }
        public virtual WFFirePriceDetail WFFirePriceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFFirePricePostponeConfirm> WFFirePricePostponeConfirm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFFirePriceRecord> WFFirePriceRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPriceInstrument> WFPriceInstrument { get; set; }
        public virtual WFPriceInfo WFPriceInfo { get; set; }
    }
}
