//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFPriceConfirmationLetter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFPriceConfirmationLetter()
        {
            this.WFPriceConfirmationLetterDetails = new HashSet<WFPriceConfirmationLetterDetails>();
        }
    
        public int WFPriceConfirmationLetterId { get; set; }
        public Nullable<int> WFContractInfoId { get; set; }
        public int UnitId { get; set; }
        public int CurrencyId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ContractName { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> PriceType { get; set; }
        public Nullable<short> ApprovalStatus { get; set; }
        public Nullable<short> TradeType { get; set; }
        public Nullable<int> PriceDetailId { get; set; }
        public int PricingUnitId { get; set; }
        public int PricingCurrencyId { get; set; }
    
        public virtual WFContractInfo WFContractInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPriceConfirmationLetterDetails> WFPriceConfirmationLetterDetails { get; set; }
    }
}
