//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFPriceQuantityScale
    {
        public int WFPriceQuantityScaleId { get; set; }
        public Nullable<int> MoneyUnitId { get; set; }
        public Nullable<int> CargoUnitId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<short> Scale { get; set; }
        public short Priority { get; set; }
    }
}
