//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFQuantityType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFQuantityType()
        {
            this.WFCommodity = new HashSet<WFCommodity>();
            this.WFCommodityQuantityUnit = new HashSet<WFCommodityQuantityUnit>();
            this.WFCommodityTypeQuantityUnit = new HashSet<WFCommodityTypeQuantityUnit>();
        }
    
        public int WFQuantityTypeId { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }
        public int QuantityKind { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> PhysicalCategory { get; set; }
        public bool IsRelateComponent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCommodity> WFCommodity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCommodityQuantityUnit> WFCommodityQuantityUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCommodityTypeQuantityUnit> WFCommodityTypeQuantityUnit { get; set; }
    }
}
