//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFReceivingClaim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFReceivingClaim()
        {
            this.WFAmountRecord = new HashSet<WFAmountRecord>();
        }
    
        public int WFReceivingClaimId { get; set; }
        public int CorporationId { get; set; }
        public int CurrencyId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string BillCode { get; set; }
        public Nullable<int> BankInfoId { get; set; }
        public string CustomerBankName { get; set; }
        public string CustomerBankAccount { get; set; }
        public string Note { get; set; }
        public string SapSequenceNumber { get; set; }
        public Nullable<System.DateTime> DaybookDate { get; set; }
        public Nullable<int> RemarksSapAmountTransaction { get; set; }
        public Nullable<int> RemarksSapAmountTransactionCategoryId { get; set; }
        public Nullable<int> SapPaymentMethod { get; set; }
        public Nullable<bool> RemarksIsSupplierCode { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsNeedReturn { get; set; }
        public Nullable<int> ExecutorId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PostingStatus { get; set; }
        public Nullable<bool> IsPay { get; set; }
        public string YGBillCode { get; set; }
        public string YGBillItemCode { get; set; }
        public Nullable<int> CustomerBankAccountId { get; set; }
        public string CorporationBankAccountCode { get; set; }
        public string CorporationBankName { get; set; }
        public bool IsSystemGenerate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFAmountRecord> WFAmountRecord { get; set; }
    }
}
