//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSafetyLink
    {
        public int WFSafetyLinkId { get; set; }
        public System.Guid Nonce { get; set; }
        public System.DateTime ExpiredTime { get; set; }
        public int WFUserId { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string BaseUrl { get; set; }
    }
}
