//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSapTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFSapTransaction()
        {
            this.WFEntitySapPart = new HashSet<WFEntitySapPart>();
            this.WFSapTransactionMultiObject = new HashSet<WFSapTransactionMultiObject>();
        }
    
        public long WFSapTransactionId { get; set; }
        public System.Guid Tid { get; set; }
        public short ServiceOperation { get; set; }
        public bool IsOut { get; set; }
        public bool IsAsync { get; set; }
        public bool NeedFeedback { get; set; }
        public bool IsMultiple { get; set; }
        public short TransactionStatus { get; set; }
        public Nullable<short> MessageOperation { get; set; }
        public Nullable<short> MessageGenericOperation { get; set; }
        public Nullable<short> MessageGenericOperationCategory { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string FromSystem { get; set; }
        public string ToSystem { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<short> FeedbackResult { get; set; }
        public string FeedbackText { get; set; }
        public short ObjectType { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public string Note { get; set; }
        public string TransferMessage { get; set; }
        public Nullable<System.Guid> RecreateNewTid { get; set; }
        public string TransferMessagePhase2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFEntitySapPart> WFEntitySapPart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSapTransactionMultiObject> WFSapTransactionMultiObject { get; set; }
    }
}
