//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSettleOptionDetail
    {
        public int WFSettleOptionDetailId { get; set; }
        public Nullable<int> WFSettleOptionId { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual WFSettleOption WFSettleOption { get; set; }
        public virtual WFSettleOptionDetailExchangeProcess WFSettleOptionDetailExchangeProcess { get; set; }
        public virtual WFSettleOptionDetailPaymentForm WFSettleOptionDetailPaymentForm { get; set; }
    }
}
