//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSettleOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFSettleOption()
        {
            this.WFContractInfo = new HashSet<WFContractInfo>();
            this.WFSettleOptionDetail = new HashSet<WFSettleOptionDetail>();
        }
    
        public int WFSettleOptionId { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public int CurrencyId { get; set; }
        public int OptionType { get; set; }
        public Nullable<int> ExchangeProcessType { get; set; }
        public Nullable<int> PaymentFormType { get; set; }
        public Nullable<decimal> ProvisionalPaymentProportion { get; set; }
        public Nullable<decimal> DepositProportion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractInfo> WFContractInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSettleOptionDetail> WFSettleOptionDetail { get; set; }
    }
}
