//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFStorageConversion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFStorageConversion()
        {
            this.WFOurPlantTransferWarehouseNotification = new HashSet<WFOurPlantTransferWarehouseNotification>();
            this.WFStorageConversionDetail = new HashSet<WFStorageConversionDetail>();
        }
    
        public int WFStorageConversionId { get; set; }
        public int StorageConversionType { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public string Note { get; set; }
        public int UnitId { get; set; }
        public bool IsDeleted { get; set; }
        public int SourceWarehouseId { get; set; }
        public Nullable<int> TargetWarehouseId { get; set; }
        public int CorporationId { get; set; }
        public int Creator { get; set; }
        public int AccountEntityId { get; set; }
        public int SalerId { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public int CommodityId { get; set; }
        public short TradeType { get; set; }
        public bool IsFinished { get; set; }
        public Nullable<int> ExchangeId { get; set; }
        public Nullable<decimal> ConvertCost { get; set; }
        public Nullable<bool> IsReceiptCodeRemain { get; set; }
        public string VoucherCode { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public Nullable<System.DateTime> TransferDeliveryDate { get; set; }
        public string TransferPlateNumber { get; set; }
        public string TransferCustomerName { get; set; }
        public string TransferDeliveryAddress { get; set; }
        public string TransferDestination { get; set; }
        public string TransferDriverName { get; set; }
        public string TransferIdNumber { get; set; }
        public string TransferTelephone { get; set; }
        public string TransferDeliveryType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFOurPlantTransferWarehouseNotification> WFOurPlantTransferWarehouseNotification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFStorageConversionDetail> WFStorageConversionDetail { get; set; }
    }
}
