//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSystemFeeConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFSystemFeeConfiguration()
        {
            this.WFSpecialFeeConfiguration = new HashSet<WFSpecialFeeConfiguration>();
        }
    
        public int WFSystemFeeConfigurationId { get; set; }
        public Nullable<int> WFCommodityId { get; set; }
        public Nullable<bool> IsSpotFee { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> SystemFeeTypeId { get; set; }
        public Nullable<bool> HasSpecialFee { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> WeightUnitId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> StorageType { get; set; }
        public Nullable<int> WFCompanyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSpecialFeeConfiguration> WFSpecialFeeConfiguration { get; set; }
        public virtual WFWarehouseCompany WFWarehouseCompany { get; set; }
    }
}
