//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSystemCodeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFSystemCodeInfo()
        {
            this.WFSystemCodeInfoConfiguration = new HashSet<WFSystemCodeInfoConfiguration>();
        }
    
        public int WFSystemCodeInfoId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> CurrentMaxCode { get; set; }
        public Nullable<short> CodeType { get; set; }
        public Nullable<short> PeriodType { get; set; }
        public Nullable<int> PeriodCount { get; set; }
        public string Name { get; set; }
        public string RuleDescription { get; set; }
        public Nullable<int> WFCodeTemplateId { get; set; }
    
        public virtual WFCodeTemplate WFCodeTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSystemCodeInfoConfiguration> WFSystemCodeInfoConfiguration { get; set; }
    }
}
