//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSystemCodeInfoConfiguration
    {
        public int WFSystemCodeInfoConfigurationId { get; set; }
        public Nullable<int> WFSystemCodeInfoId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<bool> IsBuy { get; set; }
        public Nullable<short> TradeType { get; set; }
        public Nullable<int> ContractInfoId { get; set; }
    
        public virtual WFSystemCodeInfo WFSystemCodeInfo { get; set; }
    }
}
