//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSystemConfigDetail
    {
        public int WFSystemConfigDetailId { get; set; }
        public Nullable<int> TradeType { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> ExchangeId { get; set; }
        public string WFValue { get; set; }
        public string Note { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> WFSystemConfigurationId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> Addition1 { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
    
        public virtual WFSystemConfiguration WFSystemConfiguration { get; set; }
    }
}
