//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFTradePricing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFTradePricing()
        {
            this.WFPricingConfirmDetail = new HashSet<WFPricingConfirmDetail>();
        }
    
        public int WFTradePricingId { get; set; }
        public Nullable<int> PricingRecordId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public bool IsBuy { get; set; }
        public bool IsUnpriced { get; set; }
        public Nullable<int> TradePricingType { get; set; }
        public Nullable<System.DateTime> PricingDate { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public Nullable<int> SalerId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CommodityTypeId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> MarketId { get; set; }
        public Nullable<int> InstrumentCategoryId { get; set; }
        public Nullable<int> MarketQuotePriceType { get; set; }
        public Nullable<int> InstrumentId { get; set; }
        public Nullable<decimal> PricingCargoQuantity { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<decimal> SettlementPrice { get; set; }
        public Nullable<decimal> PriceDiff { get; set; }
        public Nullable<System.DateTime> LastManipulateTime { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<int> SourceType { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public bool IsDeleted { get; set; }
        public string Notes { get; set; }
        public string Purpose { get; set; }
        public Nullable<decimal> PricingAmount { get; set; }
        public Nullable<System.Guid> ImportPricingRecord { get; set; }
    
        public virtual WFFirePriceRecord WFFirePriceRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPricingConfirmDetail> WFPricingConfirmDetail { get; set; }
    }
}
