//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFTradingStrategy
    {
        public int WFTradingStrategyId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> LastManipulationTime { get; set; }
        public bool IsDisabled { get; set; }
        public string QctKey { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public bool IsAtomic { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> DefaultCargoValueCalcType { get; set; }
    }
}
