//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFUserRequest
    {
        public int WFUserRequestId { get; set; }
        public Nullable<int> WFUserId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<short> Status { get; set; }
        public string Note { get; set; }
        public Nullable<int> ApprovalWFId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public short TradeType { get; set; }
        public Nullable<bool> IsOtherForm { get; set; }
    
        public virtual WFUser WFUser { get; set; }
    }
}
