//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFUser()
        {
            this.WFUserBusiness = new HashSet<WFUserBusiness>();
            this.WFUserCorporation = new HashSet<WFUserCorporation>();
            this.WFUserMessage = new HashSet<WFUserMessage>();
            this.WFUserRequest = new HashSet<WFUserRequest>();
            this.WFUserRole = new HashSet<WFUserRole>();
            this.WFUserTask = new HashSet<WFUserTask>();
            this.WFUserTask1 = new HashSet<WFUserTask>();
        }
    
        public int WFUserId { get; set; }
        public string Password { get; set; }
        public string LoginName { get; set; }
        public string Name { get; set; }
        public string MailAddress { get; set; }
        public Nullable<bool> IsOutofOffice { get; set; }
        public bool IsDeleted { get; set; }
        public string OfficePhone { get; set; }
        public string Fax { get; set; }
        public string WXUserId { get; set; }
        public string TrustedDevice { get; set; }
        public int NotifyingAgents { get; set; }
        public string EnglishName { get; set; }
        public Nullable<int> WFOfficeAddressId { get; set; }
        public bool IsDisabled { get; set; }
        public string SAPCode { get; set; }
        public string DdId { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastManipulationTime { get; set; }
    
        public virtual WFOfficeAddress WFOfficeAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFUserBusiness> WFUserBusiness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFUserCorporation> WFUserCorporation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFUserMessage> WFUserMessage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFUserRequest> WFUserRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFUserRole> WFUserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFUserTask> WFUserTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFUserTask> WFUserTask1 { get; set; }
    }
}
