//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFWarehousing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFWarehousing()
        {
            this.WFWarehousingDetail = new HashSet<WFWarehousingDetail>();
        }
    
        public int WFWarehousingId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<int> OurCorporationId { get; set; }
        public Nullable<int> WarehousingCompanyId { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public string Title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFWarehousingDetail> WFWarehousingDetail { get; set; }
    }
}
