//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFWarehouseEntryRecordDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFWarehouseEntryRecordDetail()
        {
            this.WFContractEntryRecordDetail = new HashSet<WFContractEntryRecordDetail>();
            this.WFDeliveryInDetailQuantity = new HashSet<WFDeliveryInDetailQuantity>();
            this.WFWarehouseStorage = new HashSet<WFWarehouseStorage>();
        }
    
        public int WFWarehouseEntryRecordDetailId { get; set; }
        public Nullable<int> WFWarehouseEntryRecordId { get; set; }
        public string CardCode { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> SpecificationId { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Creator { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> WholeOutEntryDetailUid { get; set; }
        public string AssignedNewFinancialBatchCode { get; set; }
        public Nullable<decimal> HappenedInvoiceQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractEntryRecordDetail> WFContractEntryRecordDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFDeliveryInDetailQuantity> WFDeliveryInDetailQuantity { get; set; }
        public virtual WFWarehouseEntryRecord WFWarehouseEntryRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFWarehouseStorage> WFWarehouseStorage { get; set; }
    }
}
