//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFWarehouseStorageItem
    {
        public int WFWarehouseStorageItemId { get; set; }
        public Nullable<int> WFWarehouseStorageId { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public int UnitId { get; set; }
        public bool IsValid { get; set; }
        public Nullable<int> StorageStatus { get; set; }
        public string Note { get; set; }
    
        public virtual WFWarehouseStorage WFWarehouseStorage { get; set; }
    }
}
