//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFWarehouseCalculateFeeType
    {
        public int WFWarehouseCalculateFeeTypeId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<short> StorageStandardizationType { get; set; }
        public Nullable<short> CalculateType { get; set; }
        public Nullable<int> WFCompanyId { get; set; }
    
        public virtual WFWarehouseCompany WFWarehouseCompany { get; set; }
    }
}
