//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFWarehouseEntryRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFWarehouseEntryRecord()
        {
            this.WFWarehouseEntryRecordDetail = new HashSet<WFWarehouseEntryRecordDetail>();
        }
    
        public int WFWarehouseEntryRecordId { get; set; }
        public string Code { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public int UnitId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Creator { get; set; }
        public string Note { get; set; }
        public Nullable<int> ExchangeId { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public bool IsDeleted { get; set; }
        public string DeliveryOrderCode { get; set; }
        public Nullable<int> StorageType { get; set; }
        public Nullable<int> EntryType { get; set; }
        public short ReceiveType { get; set; }
        public Nullable<int> SalerId { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public Nullable<System.DateTime> ReceiveBillTime { get; set; }
        public Nullable<System.Guid> WholeOutEntryUid { get; set; }
        public short TradeType { get; set; }
        public short WhStorageType { get; set; }
        public bool IsSystemGenerate { get; set; }
        public int EntryMapType { get; set; }
        public short CargoInseparability { get; set; }
        public Nullable<System.Guid> AccountingBatchCode { get; set; }
        public Nullable<int> TradeContractId { get; set; }
        public Nullable<bool> IsPledgeContract { get; set; }
        public Nullable<int> WFDeliveryNotificationId { get; set; }
        public Nullable<int> ConversionId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> HappenedPostingWeight { get; set; }
        public Nullable<bool> IsPosting { get; set; }
        public Nullable<int> DetailObjectType { get; set; }
        public Nullable<System.DateTime> LastManipulateTime { get; set; }
        public Nullable<System.DateTime> FirstAffectedDate { get; set; }
        public Nullable<int> LogisticsCompanyId { get; set; }
        public Nullable<decimal> ActualFreightCharges { get; set; }
        public Nullable<System.DateTime> ExpectedDocumentDate { get; set; }
    
        public virtual WFDeliveryNotification WFDeliveryNotification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFWarehouseEntryRecordDetail> WFWarehouseEntryRecordDetail { get; set; }
    }
}
