//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncTradePriced
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public Nullable<int> ContractId { get; set; }
        public string Direction { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PremiumDiscount { get; set; }
        public Nullable<decimal> ExtensionFee { get; set; }
        public Nullable<decimal> Swap { get; set; }
        public string OperationType { get; set; }
        public string Operator { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public System.Guid OriginalId { get; set; }
        public bool Unavailable { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public Nullable<int> ContractDetailId { get; set; }
        public Nullable<int> FirePriceRecordId { get; set; }
        public Nullable<decimal> FreightCharges { get; set; }
        public Nullable<decimal> ProcessingCharges { get; set; }
        public Nullable<decimal> BasisPrice { get; set; }
        public string PremiumDiscountType { get; set; }
    }
}
