//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncTradeDeliveryBatch
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> ContractId { get; set; }
        public string BatchCode { get; set; }
        public string PrecursorBatchCode { get; set; }
        public string OrigianlBatchCode { get; set; }
        public Nullable<int> PrecursorSaleContractId { get; set; }
        public Nullable<int> DeliveryId { get; set; }
        public string DeliveryCode { get; set; }
        public string Direction { get; set; }
        public string Commodity { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string Unit { get; set; }
        public string DataType { get; set; }
        public string OperationType { get; set; }
        public string Operator { get; set; }
        public System.Guid OriginalId { get; set; }
        public bool Unavailable { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string PreorderBatchCode { get; set; }
        public Nullable<int> ContractDetailId { get; set; }
        public string AccountingEntity { get; set; }
        public string Corporation { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string Warehouse { get; set; }
        public string TradeType { get; set; }
    }
}
