//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TpProjectImplementation
    {
        public int TpProjectImplementationId { get; set; }
        public Nullable<int> TpProjectId { get; set; }
        public Nullable<int> Module { get; set; }
        public Nullable<int> RelateObjectType { get; set; }
        public Nullable<int> RelateObjectId { get; set; }
        public Nullable<int> RelateCargoUnitId { get; set; }
        public Nullable<decimal> RelateCargoQuantity { get; set; }
        public Nullable<int> RelateCurrencyId { get; set; }
        public Nullable<decimal> RelateAmount { get; set; }
        public Nullable<int> ExchangeRateId { get; set; }
        public Nullable<decimal> CargoQuantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual TpProject TpProject { get; set; }
    }
}
