//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFActualApprover
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFActualApprover()
        {
            this.WFActualApprovalStep = new HashSet<WFActualApprovalStep>();
            this.WFActuaStepAction = new HashSet<WFActuaStepAction>();
        }
    
        public int WFActualApproverId { get; set; }
        public Nullable<short> ApproverType { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<int> WFUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFActualApprovalStep> WFActualApprovalStep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFActuaStepAction> WFActuaStepAction { get; set; }
    }
}
