//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFAccountEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFAccountEntity()
        {
            this.WFBusiness = new HashSet<WFBusiness>();
            this.WFCorporationDepartment = new HashSet<WFCorporationDepartment>();
            this.WFDepartmentAccountEntity = new HashSet<WFDepartmentAccountEntity>();
            this.WFDepartmentAccountEntity1 = new HashSet<WFDepartmentAccountEntity>();
        }
    
        public int WFAccountEntityId { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<int> ParentDepartmentId { get; set; }
        public Nullable<short> Type { get; set; }
        public bool IsAccounting { get; set; }
        public bool IsDeleted { get; set; }
        public string AccountingName { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastManipulationTime { get; set; }
        public bool IsDisabled { get; set; }
        public int Indicator { get; set; }
        public Nullable<bool> IsAtomicAccounting { get; set; }
        public Nullable<bool> IsHedgeAccounting { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFBusiness> WFBusiness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCorporationDepartment> WFCorporationDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFDepartmentAccountEntity> WFDepartmentAccountEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFDepartmentAccountEntity> WFDepartmentAccountEntity1 { get; set; }
    }
}
