//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFAdditionalConfiguration
    {
        public int WFAdditionalConfigurationId { get; set; }
        public short AdditionalConfigurationType { get; set; }
        public string SAPCode { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<short> Direction { get; set; }
        public Nullable<short> TaxCodeType { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<short> FeeConditionTypeCategory { get; set; }
        public string QctKey { get; set; }
        public Nullable<int> SortPriority { get; set; }
    }
}
