//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFApprovalWorkflowStepTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFApprovalWorkflowStepTemplate()
        {
            this.WFStepActionTemplate = new HashSet<WFStepActionTemplate>();
            this.WFStepConditionTemplate = new HashSet<WFStepConditionTemplate>();
            this.WFStepConditionTemplate1 = new HashSet<WFStepConditionTemplate>();
        }
    
        public int WFApprovalWorkflowStepTemplateId { get; set; }
        public Nullable<int> WFApproverTemplateId { get; set; }
        public Nullable<int> WFApprovalWorkflowTemplateId { get; set; }
        public Nullable<int> StepIndex { get; set; }
        public Nullable<short> StepType { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
    
        public virtual WFApprovalWorkflowTemplate WFApprovalWorkflowTemplate { get; set; }
        public virtual WFApproverTemplate WFApproverTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFStepActionTemplate> WFStepActionTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFStepConditionTemplate> WFStepConditionTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFStepConditionTemplate> WFStepConditionTemplate1 { get; set; }
    }
}
