//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFApprovalCancellationForm
    {
        public int WFApprovalCancellationFormId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreationTime { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<int> ApprovalStatus { get; set; }
        public int AutomationType { get; set; }
        public int OriginFlowId { get; set; }
        public string Title { get; set; }
        public string Note { get; set; }
        public Nullable<int> OriginFlowType { get; set; }
        public bool OriginFlowIsOtherForm { get; set; }
        public Nullable<int> OriginFlowObjectId { get; set; }
        public Nullable<int> ObjectCorporationId { get; set; }
        public Nullable<int> ObjectTradeType { get; set; }
    }
}
