//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFBillContentPrint
    {
        public int WFBillContentPrintId { get; set; }
        public Nullable<int> WFBillContentArchiveId { get; set; }
        public System.DateTime PrintTime { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsUnrestricted { get; set; }
    
        public virtual WFBillContentArchive WFBillContentArchive { get; set; }
    }
}
