//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFBusiness
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFBusiness()
        {
            this.WFCompanyBankInfoCommodityAccountEntity = new HashSet<WFCompanyBankInfoCommodityAccountEntity>();
            this.WFCompanyBusiness = new HashSet<WFCompanyBusiness>();
            this.WFContactCommodityAccountEntity = new HashSet<WFContactCommodityAccountEntity>();
            this.WFRoleBusiness = new HashSet<WFRoleBusiness>();
            this.WFUserBusiness = new HashSet<WFUserBusiness>();
        }
    
        public int WFBusinessId { get; set; }
        public Nullable<int> WFCommodityId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<short> TradeType { get; set; }
        public bool IsDisabled { get; set; }
    
        public virtual WFAccountEntity WFAccountEntity { get; set; }
        public virtual WFCompany WFCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCompanyBankInfoCommodityAccountEntity> WFCompanyBankInfoCommodityAccountEntity { get; set; }
        public virtual WFCommodity WFCommodity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCompanyBusiness> WFCompanyBusiness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContactCommodityAccountEntity> WFContactCommodityAccountEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFRoleBusiness> WFRoleBusiness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFUserBusiness> WFUserBusiness { get; set; }
    }
}
