//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCommodityQuantityUnit
    {
        public int WFCommodityQuantityUnitId { get; set; }
        public Nullable<int> WFCommodityId { get; set; }
        public int WFUnitId { get; set; }
        public int WFQuantityTypeId { get; set; }
        public bool IsMainQuantity { get; set; }
        public Nullable<short> Scale { get; set; }
        public Nullable<short> Priority { get; set; }
        public Nullable<int> TradeType { get; set; }
        public Nullable<int> VarietyId { get; set; }
        public string QuantityAlias { get; set; }
        public string UnitSymbolAlias { get; set; }
        public string UnitNameAlias { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public Nullable<int> RelationType { get; set; }
    
        public virtual WFCommodity WFCommodity { get; set; }
        public virtual WFComponentVariety WFComponentVariety { get; set; }
        public virtual WFQuantityType WFQuantityType { get; set; }
        public virtual WFUnit WFUnit { get; set; }
    }
}
