//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFContractWhole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFContractWhole()
        {
            this.WFContractInfo = new HashSet<WFContractInfo>();
        }
    
        public int WFContractWholeId { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
        public short TransactionType { get; set; }
        public int ContractType { get; set; }
        public int TransactionSetting { get; set; }
        public Nullable<int> SellCorporationId { get; set; }
        public Nullable<int> BuyCorporationId { get; set; }
        public string SellContractCode { get; set; }
        public string BuyContractCode { get; set; }
        public Nullable<int> SellDepartmentId { get; set; }
        public Nullable<int> BuyDepartmentId { get; set; }
        public Nullable<int> SellAccountingEntityId { get; set; }
        public Nullable<int> BuyAccountingEntityId { get; set; }
        public Nullable<int> SellSalerId { get; set; }
        public Nullable<int> BuySalerId { get; set; }
        public Nullable<int> SellCommodityId { get; set; }
        public Nullable<int> BuyCommodityId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractInfo> WFContractInfo { get; set; }
    }
}
