//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFContractPricingTerm
    {
        public int WFContractPricingTermId { get; set; }
        public Nullable<int> WFPriceInfoId { get; set; }
        public string Note { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public Nullable<int> PriceCurrencyId { get; set; }
        public Nullable<int> PriceCargoUnitId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> ParamUnitId { get; set; }
        public Nullable<bool> ParamLowerOpen { get; set; }
        public Nullable<decimal> ParamLowerBound { get; set; }
        public Nullable<bool> ParamUpperOpen { get; set; }
        public Nullable<decimal> ParamUpperBound { get; set; }
        public Nullable<decimal> Grade_RecoveryRate { get; set; }
        public Nullable<decimal> Grade_Deduction { get; set; }
        public Nullable<decimal> Penalty_UnitParam { get; set; }
        public Nullable<int> ContractPricingTermType { get; set; }
        public Nullable<int> ProcessingCharge_Type { get; set; }
    
        public virtual WFPriceInfo WFPriceInfo { get; set; }
    }
}
