//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCommodity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFCommodity()
        {
            this.WFBrand = new HashSet<WFBrand>();
            this.WFBusiness = new HashSet<WFBusiness>();
            this.WFCommodityQuantityUnit = new HashSet<WFCommodityQuantityUnit>();
            this.WFComponentVariety = new HashSet<WFComponentVariety>();
            this.WFCreditRatingDetail = new HashSet<WFCreditRatingDetail>();
            this.WFCustomerCommodity = new HashSet<WFCustomerCommodity>();
            this.WFPriceInfo = new HashSet<WFPriceInfo>();
            this.WFWarehouseStorageHistory = new HashSet<WFWarehouseStorageHistory>();
            this.WFSpecification = new HashSet<WFSpecification>();
        }
    
        public int WFCommodityId { get; set; }
        public Nullable<int> WFCommodityTypeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> StorageType { get; set; }
        public int OrderIndex { get; set; }
        public string EnglishName { get; set; }
        public Nullable<int> MainQuantityId { get; set; }
        public string SAPCode { get; set; }
        public string DisplayName { get; set; }
        public string SapDivision { get; set; }
        public string SapDivisionNote { get; set; }
        public Nullable<int> DefaultUnitId { get; set; }
        public string AccountingName { get; set; }
        public Nullable<int> RefPricingType { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFBrand> WFBrand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFBusiness> WFBusiness { get; set; }
        public virtual WFCommodityType WFCommodityType { get; set; }
        public virtual WFQuantityType WFQuantityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCommodityQuantityUnit> WFCommodityQuantityUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFComponentVariety> WFComponentVariety { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCreditRatingDetail> WFCreditRatingDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCustomerCommodity> WFCustomerCommodity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPriceInfo> WFPriceInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFWarehouseStorageHistory> WFWarehouseStorageHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSpecification> WFSpecification { get; set; }
    }
}
