//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFContractOutRecordDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFContractOutRecordDetail()
        {
            this.WFFinancialBatchOutDetail = new HashSet<WFFinancialBatchOutDetail>();
            this.WFSaleContractTradeRecord = new HashSet<WFSaleContractTradeRecord>();
        }
    
        public int WFContractOutRecordDetailId { get; set; }
        public Nullable<int> WFContractDetailInfoId { get; set; }
        public Nullable<int> WFWarehouseOutRecordDetailId { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsClearUp { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<short> ObjectType { get; set; }
        public Nullable<System.Guid> WholeOutEntryDetailUid { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> ObjectUnitWeight { get; set; }
        public string AssignedNewFinancialBatchCode { get; set; }
        public Nullable<System.Guid> GroupIdentity { get; set; }
    
        public virtual WFContractDetailInfo WFContractDetailInfo { get; set; }
        public virtual WFWarehouseOutRecordDetail WFWarehouseOutRecordDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFFinancialBatchOutDetail> WFFinancialBatchOutDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSaleContractTradeRecord> WFSaleContractTradeRecord { get; set; }
    }
}
