//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCommodityTypeQuantityUnit
    {
        public int WFCommodityTypeQuantityUnitId { get; set; }
        public Nullable<int> WFCommodityTypeId { get; set; }
        public Nullable<int> WFQuantityTypeId { get; set; }
        public Nullable<int> WFUnitId { get; set; }
        public Nullable<short> Scale { get; set; }
        public Nullable<short> Priority { get; set; }
    
        public virtual WFCommodityType WFCommodityType { get; set; }
        public virtual WFQuantityType WFQuantityType { get; set; }
        public virtual WFUnit WFUnit { get; set; }
    }
}
