//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCostPayRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFCostPayRequest()
        {
            this.WFCostPayRecord = new HashSet<WFCostPayRecord>();
        }
    
        public int WFCostPayRequestId { get; set; }
        public int PayCustomerId { get; set; }
        public int CorporationId { get; set; }
        public int CompanyBankInfoId { get; set; }
        public string PayPurpose { get; set; }
        public decimal Amount { get; set; }
        public int CurrencyId { get; set; }
        public int Status { get; set; }
        public int RequestorId { get; set; }
        public System.DateTime RequestTime { get; set; }
        public int PayType { get; set; }
        public bool IsDeleted { get; set; }
        public string Note { get; set; }
        public int CommodityId { get; set; }
        public int AccountingEntityId { get; set; }
        public int CostType { get; set; }
        public short TradeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCostPayRecord> WFCostPayRecord { get; set; }
    }
}
