//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFCreditRating
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFCreditRating()
        {
            this.WFCompany = new HashSet<WFCompany>();
            this.WFCompany1 = new HashSet<WFCompany>();
            this.WFCreditRatingDetail = new HashSet<WFCreditRatingDetail>();
            this.WFCustomerCommodity = new HashSet<WFCustomerCommodity>();
            this.WFCustomerCommodity1 = new HashSet<WFCustomerCommodity>();
        }
    
        public int WFCreditRatingId { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> AmountQuota { get; set; }
        public Nullable<decimal> QuantityQuota { get; set; }
        public bool IsBuy { get; set; }
        public Nullable<bool> IsTradeAllowed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCompany> WFCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCompany> WFCompany1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCreditRatingDetail> WFCreditRatingDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCustomerCommodity> WFCustomerCommodity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCustomerCommodity> WFCustomerCommodity1 { get; set; }
    }
}
