//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFDeliveryNotification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFDeliveryNotification()
        {
            this.WFDeliveryNotificationDetail = new HashSet<WFDeliveryNotificationDetail>();
            this.WFWarehouseEntryRecord = new HashSet<WFWarehouseEntryRecord>();
            this.WFWarehouseOutRecord = new HashSet<WFWarehouseOutRecord>();
        }
    
        public int WFDeliveryNotificationId { get; set; }
        public Nullable<bool> IsReceive { get; set; }
        public Nullable<int> DeliveryNotificationType { get; set; }
        public Nullable<int> InventoryStorageType { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> TradeType { get; set; }
        public Nullable<System.DateTime> BillTime { get; set; }
        public Nullable<System.DateTime> ExpectedActualDate { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> WarehouseOutEntryType { get; set; }
        public Nullable<int> DeliveryType { get; set; }
        public Nullable<int> IsCompleted { get; set; }
        public string Note { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverCarNumber { get; set; }
        public string IdCode { get; set; }
        public string SourceInventory { get; set; }
        public Nullable<bool> IsPledge { get; set; }
        public Nullable<System.Guid> WholeDeliveryNotificationUid { get; set; }
        public string DeliveryNotificationCode { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> DetailObjectType { get; set; }
        public Nullable<short> ApprovalStatus { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> SapShippingType { get; set; }
        public int VerifyStatus { get; set; }
        public bool IsPrePicking { get; set; }
        public string PlaceOfIssue { get; set; }
        public string PlaceOfDelivery { get; set; }
        public Nullable<int> SrcLogisticsPlaceId { get; set; }
        public Nullable<int> DstLogisticsPlaceId { get; set; }
        public Nullable<int> VehicleTransportSpecId { get; set; }
        public Nullable<int> LogisticsCompanyId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFDeliveryNotificationDetail> WFDeliveryNotificationDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFWarehouseEntryRecord> WFWarehouseEntryRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFWarehouseOutRecord> WFWarehouseOutRecord { get; set; }
    }
}
