//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFDefaultExchangeSetting
    {
        public int WFDefaultExchangeSettingId { get; set; }
        public Nullable<int> WFCurrencyPairId { get; set; }
        public int DatasourceType { get; set; }
        public Nullable<int> DatasourceId { get; set; }
        public decimal DefaultBaseUnitAmount { get; set; }
    
        public virtual WFCurrencyPair WFCurrencyPair { get; set; }
    }
}
