//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFEntityProperty
    {
        public int WFEntityPropertyId { get; set; }
        public int EntityId { get; set; }
        public string EntityPropertyValue { get; set; }
        public int WFEntityPropertyTypeId { get; set; }
    
        public virtual WFEntityPropertyType WFEntityPropertyType { get; set; }
    }
}
