//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFFinancialBatchOutDetail
    {
        public int WFFinancialBatchOutDetailId { get; set; }
        public Nullable<int> WFFinancialBatchId { get; set; }
        public Nullable<int> WFWarehouseOutRecordDetailId { get; set; }
        public decimal Weight { get; set; }
        public bool IsBoundary { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<int> WFContractOutRecordDetailId { get; set; }
    
        public virtual WFContractOutRecordDetail WFContractOutRecordDetail { get; set; }
        public virtual WFFinancialBatch WFFinancialBatch { get; set; }
        public virtual WFWarehouseOutRecordDetail WFWarehouseOutRecordDetail { get; set; }
    }
}
