//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFFirePriceDetail
    {
        public int WFPriceDetailId { get; set; }
        public Nullable<System.DateTime> FireStartDate { get; set; }
        public Nullable<System.DateTime> FireEndDate { get; set; }
        public Nullable<int> InstrumentId { get; set; }
        public bool IsFireCompleted { get; set; }
        public bool IsBuyerFire { get; set; }
        public Nullable<int> PriceCalcType { get; set; }
        public Nullable<int> PriceMarket { get; set; }
        public bool IsPostponed { get; set; }
        public Nullable<decimal> MarginRate { get; set; }
        public bool IsSwap { get; set; }
        public short PricingType { get; set; }
        public Nullable<int> FinalPriceCalculateType { get; set; }
    
        public virtual WFPriceDetail WFPriceDetail { get; set; }
    }
}
