//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFFirePriceConfirm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFFirePriceConfirm()
        {
            this.WFFirePriceRecord = new HashSet<WFFirePriceRecord>();
        }
    
        public int WFFirePriceConfirmId { get; set; }
        public string Code { get; set; }
        public bool IsDeleted { get; set; }
        public string Note { get; set; }
        public string Seller { get; set; }
        public string Buyer { get; set; }
        public string Title { get; set; }
        public string Ending { get; set; }
        public Nullable<short> ApprovalStatus { get; set; }
        public Nullable<int> WFPriceDetailId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual WFPriceDetail WFPriceDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFFirePriceRecord> WFFirePriceRecord { get; set; }
    }
}
