//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFFutureTradeRecord
    {
        public int WFFutureTradeRecordId { get; set; }
        public string AccountOrder { get; set; }
        public Nullable<System.DateTime> TradeCreationTime { get; set; }
        public string Trader { get; set; }
        public Nullable<int> TraderId { get; set; }
        public string AccountingEntity { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public string TradeAccount { get; set; }
        public Nullable<int> TradeAccountId { get; set; }
        public string Corporation { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public string Instrument { get; set; }
        public string InstrumentContractCode { get; set; }
        public Nullable<int> InstrumentId { get; set; }
        public string Market { get; set; }
        public Nullable<int> MarketId { get; set; }
        public string InstrumentCategoryContractCode { get; set; }
        public Nullable<int> InstrumentCategoryId { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<int> OrderLotsCount { get; set; }
        public Nullable<decimal> AverageFilledPrice { get; set; }
        public Nullable<int> FilledLotsCount { get; set; }
        public Nullable<System.DateTime> LastFilledTime { get; set; }
        public bool IsBuy { get; set; }
        public Nullable<bool> IsClose { get; set; }
        public Nullable<bool> IsHistory { get; set; }
        public Nullable<int> FutureTradePurpose { get; set; }
        public Nullable<System.DateTime> TradingDay { get; set; }
        public Nullable<System.DateTime> LastManipulationTime { get; set; }
        public bool IsDeleted { get; set; }
        public int SourceType { get; set; }
        public Nullable<decimal> FilledQuantity { get; set; }
        public Nullable<decimal> HedgingCoefficient { get; set; }
        public Nullable<decimal> PricingCargoQuantity { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
    
        public virtual WFInstrumentCategory WFInstrumentCategory { get; set; }
    }
}
