//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFGeneralModification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFGeneralModification()
        {
            this.WFGeneralModificationDetail = new HashSet<WFGeneralModificationDetail>();
        }
    
        public int WFGeneralModificationId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Note { get; set; }
        public int ModificationType { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<short> ApprovalStatus { get; set; }
        public bool Applied { get; set; }
        public Nullable<System.DateTime> ApplyTime { get; set; }
        public Nullable<int> SalerId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> TradeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFGeneralModificationDetail> WFGeneralModificationDetail { get; set; }
    }
}
