//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFInstrumentCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFInstrumentCategory()
        {
            this.HfFuturesOrder = new HashSet<HfFuturesOrder>();
            this.WFFutureTradeRecord = new HashSet<WFFutureTradeRecord>();
            this.WFInstrument = new HashSet<WFInstrument>();
        }
    
        public int WFInstrumentCategoryId { get; set; }
        public Nullable<int> MarketId { get; set; }
        public Nullable<int> WFCommodityTypeId { get; set; }
        public Nullable<int> WFCurrencyId { get; set; }
        public Nullable<int> WFUnitId { get; set; }
        public Nullable<int> InstrumentPeriodType { get; set; }
        public bool IsDeleted { get; set; }
        public string Code { get; set; }
        public Nullable<int> FinancialInstrumentType { get; set; }
        public string QctKey { get; set; }
        public string FriendlyName { get; set; }
        public Nullable<decimal> PriceUnitMultiple { get; set; }
        public Nullable<decimal> LotSize { get; set; }
        public Nullable<decimal> TickSize { get; set; }
        public Nullable<int> InstrumentContractFormatId { get; set; }
        public Nullable<decimal> InstrumentTaxRate { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastManipulationTime { get; set; }
        public Nullable<decimal> HedgingCoefficient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HfFuturesOrder> HfFuturesOrder { get; set; }
        public virtual WFCommodityType WFCommodityType { get; set; }
        public virtual WFCompany WFCompany { get; set; }
        public virtual WFCurrency WFCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFFutureTradeRecord> WFFutureTradeRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFInstrument> WFInstrument { get; set; }
        public virtual WFUnit WFUnit { get; set; }
    }
}
