//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFInvoiceDetailQuantity
    {
        public int WFInvoiceDetailQuantityId { get; set; }
        public Nullable<int> WFContractInvoiceId { get; set; }
        public Nullable<int> QuantityTypeId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<int> ComponentId { get; set; }
        public Nullable<int> CmqQuantityTypeId { get; set; }
        public Nullable<int> CmqUnitId { get; set; }
        public Nullable<decimal> CmqQuantity { get; set; }
        public Nullable<decimal> CmqTaxRate { get; set; }
        public Nullable<decimal> CmqPrice { get; set; }
        public Nullable<decimal> CmqAmount { get; set; }
        public Nullable<decimal> CmqTaxation { get; set; }
        public Nullable<decimal> CmqFinalQuantity { get; set; }
        public Nullable<decimal> CmqFinalPrice { get; set; }
        public Nullable<decimal> CmqFinalAmount { get; set; }
        public Nullable<decimal> FinalQuantity { get; set; }
    
        public virtual WFContractInvoice WFContractInvoice { get; set; }
    }
}
