//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFMoneyConversion
    {
        public int WFMoneyConversionId { get; set; }
        public bool IsDeleted { get; set; }
        public int Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsFinished { get; set; }
        public int MoneyConversionType { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public int CorporationId { get; set; }
        public int CounterCompanyId { get; set; }
        public Nullable<int> PayPaymentFormType { get; set; }
        public Nullable<int> ReceivePaymentFormType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public int PayCurrencyId { get; set; }
        public int ReceiveCurrencyId { get; set; }
        public decimal TotalPayAmount { get; set; }
        public decimal TotalReceiveAmount { get; set; }
        public string Note { get; set; }
        public Nullable<int> PayExchangeBillId { get; set; }
        public Nullable<System.DateTime> BillDiscountDate { get; set; }
        public Nullable<int> BillDiscountDays { get; set; }
        public Nullable<decimal> BillDiscountRate { get; set; }
        public Nullable<decimal> AnnualDays { get; set; }
        public Nullable<decimal> DiscountRatio { get; set; }
        public Nullable<int> ReceiveExchangeRate { get; set; }
        public Nullable<int> ReceiveExchangeBillId { get; set; }
        public decimal TotalPayPresentValue { get; set; }
        public decimal TotalReceivePresentValue { get; set; }
        public Nullable<decimal> PayCurrencyFee { get; set; }
    }
}
