//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFMultiPrecursorBatch
    {
        public int WFMultiPrecursorBatchId { get; set; }
        public Nullable<int> SuccessorBatchId { get; set; }
        public Nullable<int> PrecursorBatchId { get; set; }
        public Nullable<decimal> SuccessorUnitQuantity { get; set; }
    
        public virtual WFFinancialBatch WFFinancialBatch { get; set; }
        public virtual WFFinancialBatch WFFinancialBatch1 { get; set; }
    }
}
