//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFOrderInfo
    {
        public int WFOrderInfoId { get; set; }
        public Nullable<int> WFContractInfoId { get; set; }
        public Nullable<int> StatusOfOrder { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public bool IsBuy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> SalerId { get; set; }
        public string Note { get; set; }
        public bool IsFurtureDelivery { get; set; }
        public bool IsInvoiceThisMonth { get; set; }
    
        public virtual WFContractInfo WFContractInfo { get; set; }
    }
}
