//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFPriceInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFPriceInfo()
        {
            this.WFContractDetailInfo = new HashSet<WFContractDetailInfo>();
            this.WFContractInfo = new HashSet<WFContractInfo>();
            this.WFContractPricingTerm = new HashSet<WFContractPricingTerm>();
            this.WFPriceDetail = new HashSet<WFPriceDetail>();
        }
    
        public int WFPriceInfoId { get; set; }
        public bool IsDeleted { get; set; }
        public int PriceMakingType { get; set; }
        public int UnitId { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<short> Scale { get; set; }
        public int PricingUnitId { get; set; }
        public int PricingCurrencyId { get; set; }
        public Nullable<short> PricingScale { get; set; }
        public Nullable<int> TempExchangeRateId { get; set; }
    
        public virtual WFCommodity WFCommodity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractDetailInfo> WFContractDetailInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractInfo> WFContractInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractPricingTerm> WFContractPricingTerm { get; set; }
        public virtual WFCurrency WFCurrency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPriceDetail> WFPriceDetail { get; set; }
        public virtual WFUnit WFUnit { get; set; }
    }
}
