//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFRoleBusiness
    {
        public int WFRoleBusinessId { get; set; }
        public int WFRoleInfoId { get; set; }
        public Nullable<int> WFBusinessId { get; set; }
        public bool IsDisabled { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> AccountEntityId { get; set; }
        public Nullable<int> CommodityTypeId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> Module { get; set; }
        public string Note { get; set; }
    
        public virtual WFBusiness WFBusiness { get; set; }
        public virtual WFRoleInfo WFRoleInfo { get; set; }
    }
}
