//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFRoleConditionConfiguration
    {
        public int WFRoleConditionConfigurationId { get; set; }
        public Nullable<int> ApproverTemplateId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> TradeType { get; set; }
        public Nullable<int> ApprovalType { get; set; }
        public Nullable<int> ApproverActionType { get; set; }
        public string Users { get; set; }
        public string Note { get; set; }
    
        public virtual WFApproverTemplate WFApproverTemplate { get; set; }
    }
}
