//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSapConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFSapConfiguration()
        {
            this.WFSapAmountCategoryCommodity = new HashSet<WFSapAmountCategoryCommodity>();
        }
    
        public int WFSapConfigurationId { get; set; }
        public bool IsDeleted { get; set; }
        public short SapConfigurationType { get; set; }
        public string SapCode { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<bool> SapZxxtEnabled { get; set; }
        public Nullable<int> SapAmountCategoryType { get; set; }
        public Nullable<bool> SapAmountTransactionIsPay { get; set; }
        public Nullable<int> SapAmountTransactionPayPurposeType { get; set; }
        public Nullable<int> SapAmountTransactionCompanyCodeType { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> SapCompanyCodeCurrencyId { get; set; }
        public Nullable<bool> SapAmountTransactionInitialPosted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSapAmountCategoryCommodity> WFSapAmountCategoryCommodity { get; set; }
    }
}
