//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSettleOptionDetailExchangeProcess
    {
        public int WFSettleOptionDetailId { get; set; }
        public int ExchangeProcessType { get; set; }
    
        public virtual WFSettleOptionDetail WFSettleOptionDetail { get; set; }
        public virtual WFSodEpConditionalRelease WFSodEpConditionalRelease { get; set; }
        public virtual WFSodEpDocumentsAgainstAcceptance WFSodEpDocumentsAgainstAcceptance { get; set; }
        public virtual WFSodEpDocumentsAgainstPayment WFSodEpDocumentsAgainstPayment { get; set; }
        public virtual WFSodEpLetterOfCredit WFSodEpLetterOfCredit { get; set; }
        public virtual WFSodEpAmountFirst WFSodEpAmountFirst { get; set; }
    }
}
