//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSettlementRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFSettlementRequest()
        {
            this.WFPayRequest = new HashSet<WFPayRequest>();
            this.WFSettlementRequestDetail = new HashSet<WFSettlementRequestDetail>();
        }
    
        public int WFSettlementRequestlId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> RequestorId { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool IsPay { get; set; }
        public int CurrencyId { get; set; }
        public bool IsFinished { get; set; }
        public Nullable<int> PayType { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public string Note { get; set; }
        public Nullable<int> SalerId { get; set; }
        public short TradeType { get; set; }
        public bool IsSystemGenerate { get; set; }
        public int BalanceMapType { get; set; }
        public Nullable<int> SettlementDetailObjectType { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPayRequest> WFPayRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSettlementRequestDetail> WFSettlementRequestDetail { get; set; }
    }
}
