//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSodEpDocumentsAgainstAcceptance
    {
        public int WFSettleOptionDetailId { get; set; }
        public Nullable<int> BuyerBankId { get; set; }
        public Nullable<int> SalerBankId { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual WFSettleOptionDetailExchangeProcess WFSettleOptionDetailExchangeProcess { get; set; }
    }
}
