//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSpotReceiptConvertDetailInfo
    {
        public int WFSpotReceiptConvertDetailInfoId { get; set; }
        public Nullable<int> WFSpotReceiptConvertInfoId { get; set; }
        public Nullable<int> WFWarehouseStorageId { get; set; }
        public Nullable<decimal> RequestWeight { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
    
        public virtual WFSpotReceiptConvertInfo WFSpotReceiptConvertInfo { get; set; }
        public virtual WFWarehouseStorage WFWarehouseStorage { get; set; }
    }
}
