//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSpecialFeeConfiguration
    {
        public int WFSpecialFeeConfigurationId { get; set; }
        public Nullable<int> WFWarehouseFeeId { get; set; }
        public Nullable<int> WFWarehouseId { get; set; }
        public Nullable<int> WFCommodityId { get; set; }
        public Nullable<decimal> StartDay { get; set; }
        public Nullable<decimal> EndDay { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> SpecialDate { get; set; }
        public Nullable<int> SystemFeeTypeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual WFSystemFeeConfiguration WFSystemFeeConfiguration { get; set; }
    }
}
