//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFStepConditionTemplate
    {
        public int WFStepConditionId { get; set; }
        public Nullable<int> PreviousWFApprovalWorkflowStepId { get; set; }
        public Nullable<int> NextWFApprovalWorkflowStepId { get; set; }
        public Nullable<int> WFConditionId { get; set; }
        public Nullable<short> Action { get; set; }
        public Nullable<short> Result { get; set; }
        public string ConditionNote { get; set; }
        public Nullable<short> MemberPassType { get; set; }
    
        public virtual WFApprovalWorkflowStepTemplate WFApprovalWorkflowStepTemplate { get; set; }
        public virtual WFApprovalWorkflowStepTemplate WFApprovalWorkflowStepTemplate1 { get; set; }
        public virtual WFCondition WFCondition { get; set; }
    }
}
