//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSupplementalAgreement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFSupplementalAgreement()
        {
            this.WFSupplementalAgreementDetail = new HashSet<WFSupplementalAgreementDetail>();
        }
    
        public int NewContractId { get; set; }
        public Nullable<int> OriginContractId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        public int ContractContinuationType { get; set; }
    
        public virtual WFContractInfo WFContractInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSupplementalAgreementDetail> WFSupplementalAgreementDetail { get; set; }
    }
}
