//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSystemLog
    {
        public int WFSystemLogId { get; set; }
        public Nullable<int> LogType { get; set; }
        public string ObjectType { get; set; }
        public string ObjectId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> LogTime { get; set; }
        public string ObjectContent { get; set; }
    }
}
