//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSystemFee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFSystemFee()
        {
            this.WFContractFee = new HashSet<WFContractFee>();
            this.WFFeeRecord = new HashSet<WFFeeRecord>();
        }
    
        public int WFSystemFeeId { get; set; }
        public Nullable<int> WFSystemFinanceAccountId { get; set; }
        public string FeeName { get; set; }
        public Nullable<int> FeeType { get; set; }
        public string Note { get; set; }
        public Nullable<bool> AbleAutoGenerate { get; set; }
        public Nullable<int> AutoFeeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractFee> WFContractFee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFFeeRecord> WFFeeRecord { get; set; }
        public virtual WFSystemFinanceAccount WFSystemFinanceAccount { get; set; }
    }
}
