//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFSystemConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFSystemConfiguration()
        {
            this.WFSystemConfigDetail = new HashSet<WFSystemConfigDetail>();
        }
    
        public string WFKey { get; set; }
        public string WFValue { get; set; }
        public string Note { get; set; }
        public string Name { get; set; }
        public Nullable<int> ConfCategory { get; set; }
        public int WFSystemConfigurationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSystemConfigDetail> WFSystemConfigDetail { get; set; }
    }
}
