//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFTradeInstruction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFTradeInstruction()
        {
            this.WFTradeInstructionDetail = new HashSet<WFTradeInstructionDetail>();
            this.WFTradeInstructionRelation = new HashSet<WFTradeInstructionRelation>();
        }
    
        public int WFTradeInstructionId { get; set; }
        public Nullable<int> TradeInstructionType { get; set; }
        public string TradeInstructionCode { get; set; }
        public Nullable<int> TradeInstructionDirection { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> CommodityTypeId { get; set; }
        public Nullable<int> SubjectUnitId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> AccountingEntityId { get; set; }
        public bool RequireHedging { get; set; }
        public int TradeInstructionStatus { get; set; }
        public string Notes { get; set; }
        public string RawText { get; set; }
        public string Serial { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public Nullable<System.DateTime> SubmitTime { get; set; }
        public bool IsSystemGenerate { get; set; }
        public Nullable<int> OldTradeInstructionId { get; set; }
        public Nullable<System.DateTime> PriceFilledTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFTradeInstructionDetail> WFTradeInstructionDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFTradeInstructionRelation> WFTradeInstructionRelation { get; set; }
    }
}
