//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFTradeAccount
    {
        public int WFTradeAccountId { get; set; }
        public string QctKey { get; set; }
        public string Name { get; set; }
        public Nullable<int> TradeAccountTypeId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> AccountCurrencyId { get; set; }
        public Nullable<int> BrokerId { get; set; }
        public bool IsVirtual { get; set; }
        public string Notes { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreationTime { get; set; }
        public System.DateTime LastManipulationTime { get; set; }
        public bool IsDisabled { get; set; }
        public int Indicator { get; set; }
    }
}
