//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFUnit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFUnit()
        {
            this.WFCommodityQuantityUnit = new HashSet<WFCommodityQuantityUnit>();
            this.WFCommodityTypeQuantityUnit = new HashSet<WFCommodityTypeQuantityUnit>();
            this.WFInstrumentCategory = new HashSet<WFInstrumentCategory>();
            this.WFPriceInfo = new HashSet<WFPriceInfo>();
        }
    
        public int WFUnitId { get; set; }
        public string Symbol { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }
        public string EnglishName { get; set; }
        public int QuantityKind { get; set; }
        public string InformalSymbol { get; set; }
        public string InformalName { get; set; }
        public string InformalEnglishName { get; set; }
        public string SapCode { get; set; }
        public string AccountingName { get; set; }
        public Nullable<int> SpecialUnit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCommodityQuantityUnit> WFCommodityQuantityUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFCommodityTypeQuantityUnit> WFCommodityTypeQuantityUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFInstrumentCategory> WFInstrumentCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFPriceInfo> WFPriceInfo { get; set; }
    }
}
