//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFWarehouseOutRecordDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFWarehouseOutRecordDetail()
        {
            this.WFContractOutRecordDetail = new HashSet<WFContractOutRecordDetail>();
            this.WFFinancialBatchOutDetail = new HashSet<WFFinancialBatchOutDetail>();
            this.WFOutRecordAssistantMeasureInfo = new HashSet<WFOutRecordAssistantMeasureInfo>();
            this.WFWhStorageFlowTrack = new HashSet<WFWhStorageFlowTrack>();
        }
    
        public int WFWarehouseOutRecordDetailId { get; set; }
        public Nullable<int> WFWarehouseOutRecordId { get; set; }
        public string CardCode { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> SpecificationId { get; set; }
        public Nullable<int> Volume { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Creator { get; set; }
        public string Note { get; set; }
        public bool IsClearUp { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> WholeOutEntryDetailUid { get; set; }
        public Nullable<int> WFWarehouseStorageId { get; set; }
        public string AssignedNewFinancialBatchCode { get; set; }
        public Nullable<decimal> HappenedInvoiceQuantity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFContractOutRecordDetail> WFContractOutRecordDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFFinancialBatchOutDetail> WFFinancialBatchOutDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFOutRecordAssistantMeasureInfo> WFOutRecordAssistantMeasureInfo { get; set; }
        public virtual WFWarehouseOutRecord WFWarehouseOutRecord { get; set; }
        public virtual WFWarehouseStorage WFWarehouseStorage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFWhStorageFlowTrack> WFWhStorageFlowTrack { get; set; }
    }
}
