//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFWarehouseOutOrder
    {
        public int WFWarehouseOutOrderId { get; set; }
        public Nullable<int> WFWarehouseOutRecordId { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public Nullable<decimal> TotalVolume { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public int UnitId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverIdenityCard { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Creator { get; set; }
        public string Note { get; set; }
        public string WeightMemos { get; set; }
        public bool IsSpot { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual WFWarehouseOutRecord WFWarehouseOutRecord { get; set; }
    }
}
