//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFWarehouseStorage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WFWarehouseStorage()
        {
            this.WFFinancialBatchInventory = new HashSet<WFFinancialBatchInventory>();
            this.WFSpotReceiptConvertDetailInfo = new HashSet<WFSpotReceiptConvertDetailInfo>();
            this.WFStorageAssistantMeasureInfo = new HashSet<WFStorageAssistantMeasureInfo>();
            this.WFWarehouseOutRecordDetail = new HashSet<WFWarehouseOutRecordDetail>();
            this.WFWarehouseStorageItem = new HashSet<WFWarehouseStorageItem>();
            this.WFWhStorageFlowTrack = new HashSet<WFWhStorageFlowTrack>();
            this.WFWhStorageFlowTrack1 = new HashSet<WFWhStorageFlowTrack>();
        }
    
        public int WFWarehouseStorageId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<int> PurchaseContractDetailId { get; set; }
        public Nullable<int> SalerId { get; set; }
        public Nullable<int> CommodityId { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> SpecificationId { get; set; }
        public decimal Weight { get; set; }
        public int UnitId { get; set; }
        public bool IsSaleOut { get; set; }
        public decimal AailableWeight { get; set; }
        public Nullable<int> ExchangeId { get; set; }
        public Nullable<int> SourceType { get; set; }
        public bool IsPledge { get; set; }
        public Nullable<int> CorporationId { get; set; }
        public string ReceiptQualityStatus { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> AccountEntityId { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public bool IsExistedOutsideSystem { get; set; }
        public Nullable<decimal> LossWeight { get; set; }
        public string Note { get; set; }
        public bool IsAllowedEdit { get; set; }
        public bool IsActualWeight { get; set; }
        public Nullable<decimal> PledgeWeight { get; set; }
        public Nullable<System.DateTime> ActualEntryTime { get; set; }
        public Nullable<int> SavePlaceType { get; set; }
        public string DeliveryStatusCode { get; set; }
        public Nullable<short> WhStorageType { get; set; }
        public string SavePlaceIdentity { get; set; }
        public bool IsTemphold { get; set; }
        public Nullable<decimal> TempholdWeight { get; set; }
        public Nullable<decimal> TotalWeight { get; set; }
        public string BatchImportIdentity { get; set; }
        public short TradeType { get; set; }
        public Nullable<int> WFWarehouseEntryRecordDetailId { get; set; }
        public short MeasureType { get; set; }
        public string GroupCode { get; set; }
        public string StorageCode { get; set; }
        public string GroupDocumentIdentity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFFinancialBatchInventory> WFFinancialBatchInventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFSpotReceiptConvertDetailInfo> WFSpotReceiptConvertDetailInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFStorageAssistantMeasureInfo> WFStorageAssistantMeasureInfo { get; set; }
        public virtual WFWarehouseEntryRecordDetail WFWarehouseEntryRecordDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFWarehouseOutRecordDetail> WFWarehouseOutRecordDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFWarehouseStorageItem> WFWarehouseStorageItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFWhStorageFlowTrack> WFWhStorageFlowTrack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WFWhStorageFlowTrack> WFWhStorageFlowTrack1 { get; set; }
    }
}
