//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tool.EF.DBObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class WFWhStorageFlowTrack
    {
        public int WFWhStorageFlowTrackId { get; set; }
        public Nullable<int> SourceWarehouseStorageId { get; set; }
        public Nullable<int> TargetWarehouseStorageId { get; set; }
        public Nullable<int> ObjectId { get; set; }
        public Nullable<int> ObjectType { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public int UnitId { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string Note { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> ActualWeight { get; set; }
        public string DeliveryOrderCode { get; set; }
        public Nullable<decimal> LeftPledgedWeight { get; set; }
        public Nullable<decimal> ToWeight { get; set; }
        public Nullable<int> ToUnitId { get; set; }
        public Nullable<int> WFWarehouseOutRecordDetailId { get; set; }
        public Nullable<System.Guid> WhFlowTrackWholeUid { get; set; }
    
        public virtual WFWarehouseOutRecordDetail WFWarehouseOutRecordDetail { get; set; }
        public virtual WFWarehouseStorage WFWarehouseStorage { get; set; }
        public virtual WFWarehouseStorage WFWarehouseStorage1 { get; set; }
    }
}
